### ISSUE TITLE
software test checking that dx != dy cases are handled correctly

### ISSUE THREAD

**Issue by bueler** [pism/pism#105]
There is an invariance principle that is testable, namely that PISM should work on dx!=dy grids and that it should produce the same output on a dx=A,dy=B grid as it does on an dx=B,dy=A grid, all other options being the same.

The purpose of a test is to make sure there is no code that looks like

```
dbdx = (bed(i+1,j) - bed(i,j)) / grid.dx;   // correct
dbdy = (bed(i,j+1) - bed(i,j)) / grid.dx;   // TYPO: dx --> dy not made
```

Such code might work in all tests, because many of them use dx=dy grids, but fail in actual use in some case where dx!=dy.  The above code fragment could appear in PISMComponent code which does not run under (e.g.) pisms.

My proposed test is to build a small dx!=dy and Mx!=My grid, run PISM while turning on every mechanism you can think of that might need testing and which generates model_state output.  Then run again with x,y switched.  Then compare output files after switching one back.

Feel free to close this issue if this is (1) already done sufficiently or (2) unwise or too painful to implement.

**Comment by ckhroulev** [comment]
This is great advice but yes, it would be too painful to implement.

I added something along these lines to the section titled "Writing tests" in our contributing guidelines and will try to keep this in mind as I add more tests.
