### ISSUE TITLE
Improve pismmerge

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#106]
The more I think about handling very large extra files, the more I think the following would be useful:

Instead (or in addition to?) having pismmerge merging a predefined subregion, it would be useful to merge by variable, that is, to create 1 extra file per variable. The file should contain the variable, lat, lon, history, mapping.

I think timeseries files of individual variables are easier and more convenient to deal with, and simple to archive and handle. If the files still get too big, files could be split into, e.g. yearly files. This would be similar to what climate models are doing, I believe. Thoughts?

**Comment by ckhroulev** [comment]
I just removed `pismmerge`: it's more trouble than it's worth.
