### ISSUE TITLE
install PISM header files in one location

### ISSUE THREAD

**Issue by bueler** [pism/pism#166]
From an email from Bob Fischer:

[Modifying src/pismr.cc to a new driver works,] But getting it to work requires obscenely too many compiler flags added to my build commands (see at end of message).  I would suggest:
1. Put all the header files into a directory tree that gets installed in an `include/` directory (right now they're not installed at all).  For example, if PISM is to be installed in the prefix `/opt/local`, then include files should go into `/opt/local/include/pism/...`  Accessing PISM include files would be done with one compiler flag `-I/opt/local`.   The include files would then be included, for example, as follows:

```
#include <petsc.h>
#include <pism/util/IceGrid.hh>
#include <pism/base/iceModel.hh>
#include <pism/util/pism_options.hh>
#include <pism/coupler/atmosphere/PAFactory.hh>
#include <pism/coupler/ocean/POFactory.hh>
#include <pism/coupler/surface/PSFactory.hh>
```

With a bit of organized effort, a sed script can be used to search-and-replace includes as appropriate.
1. Link things together into fewer libraries.  Unless there REALLY is a forseeable use case in which someone will NEED to link to one library and not another --- for example, if part of the PISM code is optional AND introduces a bunch of extra dependencies that most people won't need to install.  But I get the sense that PISM is for the most part not like that, and could be combined into one, or a small number of libraries.

Sincerely,
  Bob Fischer

[PS:  My long build command:]

```
PETSC_HOME=$HOME/opt/petsc-3.3-p7
PETSC_ARCH=$PETSC_HOME/arch-darwin-c-opt
export PETSC_CFLAGS="-I$PETSC_ARCH/include -I$PETSC_HOME/include"
export PETSC_LIBS="-L$PETSC_ARCH/lib -lpetsc"

export GSL_HOME=/opt/local
export GSL_CFLAGS="-I $GSL_HOME/include"
export GSL_LIBS="-L$GSL_HOME/lib -lgslcblas"

PISM_SRC=$HOME/git/pism/src
PISM_HOME=$HOME/opt/pism
export PISM_CFLAGS="$PETSC_CFLAGS -I$PISM_SRC/base -I$PISM_SRC/base/stressbalance -I$PISM_SRC/base/util -I$PISM_SRC/base/util/io -I$PISM_SRC/base/energy -I$PISM_SRC/base/rheology -I$PISM_SRC/base/basal_strength -I$PISM_SRC/earth -I$PISM_SRC/coupler -I$PISM_SRC/coupler/atmosphere -I$PISM_SRC/coupler/surface -I$PISM_SRC/coupler/ocean -I$PISM_SRC/coupler/util -I$PISM_SRC/udunits"
export PISM_LIBS="$PETSC_LIBS -L$PISM_HOME/lib/pism -lpismbase -lpismearth -lpismboundary -lpismstressbalance -lpismflowlaws -lpismutil -lpismudunits $PISM_SRC/../build/src/libpismrevision.a $GSL_LIBS"
```

**Comment by citibeth** [comment]
I see that this is mostly done in PISM v0.7.  However... I'm still writing:

```
#include <petsc.h>
#include <util/IceGrid.hh>
#include <base/iceModel.hh>

#include <util/pism_options.hh>
#include <atmosphere/PAFactory.hh>
#include <ocean/POFactory.hh>
#include <surface/PSFactory.hh>

#include <util/PISMTime.hh>
```

instead of:

```
#include <pism/petsc.h>
#include <pism/util/IceGrid.hh>
#include <pism/base/iceModel.hh>

#include <pism/util/pism_options.hh>
#include <pism/atmosphere/PAFactory.hh>
#include <pism/ocean/POFactory.hh>
#include <pism/surface/PSFactory.hh>

#include <pism/util/PISMTime.hh>
```

This issue makes sense when one considers all the other #include statements in my code.  If every package put stuff in "util/", "base/", etc. then they'd be walking all over each others' toes pretty quickly.

**Comment by citibeth** [comment]
Looks good!  Just one more concern...

The PISM source files INSIDE the PISM build include things without the `pism/` prefix:
```
#include "base/hydrology/PISMHydrology.hh"
#include "base/stressbalance/PISMStressBalance.hh"
#include "base/util/IceGrid.hh"
```

I think it would be best if the `#include` directives used inside and outside the PISM source tree were the same.

**Comment by ckhroulev** [comment]
> I think it would be best if the `#include` directives used inside and outside the PISM source tree were the same.

Do you mind explaining why?

**Comment by citibeth** [comment]
1. It removes an unnecessary distinction and "surprising" aspect of the
code.  Sure it's easy to remember when working on PISM.  But I have to work
with dozens of packages, and the *idiosyncrasies*
<https://www.google.com/search?q=idiosyncrasies&spell=1&sa=X&ved=0ahUKEwjilrzQho3QAhUG6WMKHaYLABEQvwUIGigA>
add
up.

2. It makes it clear that the intention for users of PISM is to use the
flag `-I/pismhom/include`, not `-I/pismhome/include/pism`.  This exact
confusion has caused build problems for a variety of packages in the past.

**Comment by citibeth** [comment]
Here's why (see below).  There are a few ways to resolve this; your input on this would be great.

1. Use `#include <pism/...>` internally in all PISM code.
2. Change my build to add `-I.../include/pism` instead of `-I.../include`, then remove the `pism/` from my `#include` directives.
3. Leave all code as-is and use the flags `-I.../include/pism -I.../include` in my build.

Note that all my include files are under a toplevel `icebin/` directory.  Therefore, (2) and (3) could cause potential conflicts between my include files and PISM's include files; since PISM has a `pism/icebin` directory.  (Similarly, IceBin has an `icebin/pism` directory).

For this reason, I think that Option (1) would be best/cleanest in the long run.

```
[ 14%] Building CXX object slib/CMakeFiles/icebin.dir/icebin/GCMCoupler.cpp.o
In file included from /home2/rpfische/git/icebin/slib/icebin/pism/IceModel_PISM.hpp:25:0,
                 from /home2/rpfische/git/icebin/slib/icebin/GCMCoupler.cpp:28:
/home2/rpfische/spack3/opt/spack/linux-centos7-x86_64/gcc-4.9.3/pism-local-hnayi4h75xrdvnjnzqrcpjk2xhedkdji/include/pism/base/util/IceGrid.hh:28:32: fatal error: base/util/Context.hh: No such file or directory
 #include "base/util/Context.hh"
                                ^
compilation terminated.
make[2]: *** [slib/CMakeFiles/icebin.dir/icebin/GCMCoupler.cpp.o] Error 1
make[1]: *** [slib/CMakeFiles/icebin.dir/all] Error 2
make: *** [all] Error 2
```

`IceModel_PISM.hpp` looks like:
```
#pragma once

// --------------------------------
// PISM Includes... want to be included first
#include <petsc.h>
#include <petscvec.h>
#include <pism/base/util/IceGrid.hh>
#include <pism/base/util/iceModelVec.hh>
#include <pism/base/iceModel.hh>

#include <pism/base/util/pism_options.hh>
#include <pism/coupler/atmosphere/PAFactory.hh>
#include <pism/coupler/ocean/POFactory.hh>
#include <pism/coupler/surface/PSFactory.hh>

#include <pism/base/util/PISMTime.hh>

#include <pism/icebin/PetscContext.hh>
#include <pism/icebin/IBIceModel.hh>
#include <pism/icebin/VecBundleWriter.hh>
#include <pism/icebin/IBSurfaceModel.hh>
#include <pism/base/util/petscwrappers/PetscInitializer.hh>
// --------------------------------
#include <mpi.h>
#include <icebin/GCMCoupler.hpp>
#include <memory>
...
```

**Comment by ckhroulev** [comment]
Fixed in `dev` and the next release (coming soon).
