### ISSUE TITLE
add PISMStressBalance that reads 3D velocities from file; useful for energy-only runs

### ISSUE THREAD

**Issue by bueler** [pism/pism#171]
This issue is motivated by email from T. Kleiner asking "if there is an easy way to force the velocities and only compute the enthalpy evolution in PISM".  It would be a useful mode to have in PISM for some users.

A PISMStressBalance object (http://www.pism-docs.org/doxy/html/classPISMStressBalance.html) will supply a 3D velocity field to the energy conservation submodel.  Thereby the advection term in the conservation of energy equation can be computed.  Normally PISMStressBalance uses geometry (including surface slope and thickness) and stress boundary conditions (including basal material yield stress and calving front boundary stresses) to compute the velocity field.

Here we want to test only the energy conservation code, bypassing any solution of a stress balance, but still having the desired advection, both horizontal and vertical, in the energy conservation equation.

So the proposal is to have a PISMStressBalance read the 3D velocities from a file and hold them fixed.  This is only a good idea if the geometry of the ice sheet is also held fixed; i.e. -no_mass should at least be recommended for this mode.  These velocities could be put into the file by a previous PISM run using -o_size big, for example, or by a script or other agent writing a NetCDF file.

**Comment by ckhroulev** [comment]
We don't need a stress balance module like this one any more: these days it's easy to create an energy model that does not use a stress balance instance. See [`test/energy_model.py`](https://github.com/pism/pism/blob/f49de85b15eb00e6e209d53ee77fa4486a0e314e/test/energy_model.py) for an example.
