### ISSUE TITLE
allow offline-runs of earth deformation model

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#181]
There are applications where we want to run the earth deformation model standalone, i.e. without ice dynamics. More specifically, we may only be interested in the end state, not in the transient evolution.

I suggest to look at the equations in the earth deformation code and evaluate if the equations could be integrated with respect to time to allow for fast computation of the end state. Maybe something like

``` bash
pismearthdef -in_topg topg.nc in_thk thk.nc -target_thk target_thk.nc out_topg.nc
```

is possible. I.e. we compute the end state of topg given an input topg and ice thickness, and a target ice thickness. This would allow for a fast computation of the relaxed bed topography of a deglaciated ice sheet.

**Comment by ckhroulev** [comment]
Offline runs of bed deformation models are pretty easy to set up these days: see [`test/bed_deformation.py`](https://github.com/pism/pism/blob/0d3a7432db946c9ca32ff9cabe9b7352dfd546fa/test/bed_deformation.py) for an example.

Fast computation of relaxed bed topography in the context of the Lingle-Clark model is also possible without too much effort. I am closing this for now; please re-open if you have *specific* ideas related to this.
