### ISSUE TITLE
API for Coupling with GCM

### ISSUE THREAD

**Issue by citibeth** [pism/pism#196]
We would like to two-way couple PISM to a GCM step by step, compiling the two into one executable.  This introduces the following requirements, for which we propose a draft API (almost certainly subject to change as this turns into a working system):
1. It must be possible to timestep PISM explicitly.  Rather than calling `IceModel::run()`, we need a way to step forward to a particular time.  We propose:

``` c++
    /* Steps forward to the time t */
    IceModel::run_to(double t)
```
1. We need to give our own atmosphere climate to PISM, rather than reading it from any files.  We propose `ConstSGivenClimate` to replace `PSGivenClimate`.  `ConstSGivenClimate` is essentially a buffer that stores ONE set of SMB and energy fluxes, and then reports that as the flux whenever asked (I believe the asking happens in PISM through the methods `ice_surface_mass_flux()` and `ice_surface_temperature()`).  No interpolation, averaging or anything else fancy should be needed.
     The GCM will change the fluxes provided by `ConstSGivenClimate` at the beginning of each timestep.  This will be done via `set_surface_mass_flux()` and `set_surface_temperature()` methods.
2. There needs to be a way to initialize PETSc and PISM outside of a `main()` program.  For now, PISM is the only user of PETSc.  We believe that no additional functionality is needed here.  We intend to construct `argv[]` and `argc` variables programmatically, and then send them to `PetscInitialize()`.  We will use information in a related recent issue (#189) to get the communicators set up correctly.
   There does not seem to be an obvious way to initialize PISM without "pretending" to set up command line options.  It feels a bit kludgy.  But no matter, the existing ways should work.
3. There needs to be a way to construct the PISM classes DIFFERENTLY from how they are constructed through the normal command-line initialization.  In particular, we would like to instantiate an instance of `ConstSGivenClimate`, and use that in place of `PSGivenClimate`.  We don't know exactly how this is best accomplished, or what `ConstSGivenClimate` should subclass.  We suggest a method `IceModel::attach_sclimate()`, but that is very much just a guess at how it might work.
4. We will need to replace `POGivenClimate` as well.  But first things first...

Below is a sample of a test program we would envision to write with this API.  The program should do approximately the same thing as `pismr.cc` --- except it would read its forcings out of a file of my own specification.  (This file is just for testing, it would be replaced by no file when integrated with the GCM).

``` c++
class ConstSGivenClimate : public PSModifier
{
public:
    ConstSGivenClimate(IceGrid &g, const NCConfigVariable &conf);

    /** Does nothing */
    void attach_atmosphere_model(PISMAtmosphereModel *input);

    /** Does nothing */
    PetscErrorCode init(PISMVars &vars);

    /** Does nothing */
    PetscErrorCode update(PetscReal my_t, PetscReal my_dt);

    /** ModelE will call this with the SMB it has computed over a
    coupling timestep.  The call will be made from ONLY ONE MPI node,
    the array must be distributed properly according to PISM's domain
    decomposition. */
    void set_surface_mass_flux(blitz::Array<double,2> const &surface);
    void set_surface_temperature(blitz::Array<double,2> const &surface);

    /** Used within PISM to retrieve values stored by
    set_surface_mass_flux(), etc. */
    PetscErrorCode ice_surface_mass_flux(IceModelVec2S &result);
    PetscErrorCode ice_surface_temperature(IceModelVec2S &result);

    // ------------------------------------

private:
    /** Stores the values set by set_xyz() methods above */
    IceModelVec2S surface_mass_flux, surface_temperature;
};


int main(int argc, char *argv[]) {
...
     IceGrid g(com, rank, size, config);
     IceModel m(g, config, overrides);

printf("start = %f\n", g.time->start());
printf("end = %f\n", g.time->end());


     ierr = m.setExecName("pismr"); CHKERRQ(ierr);

     ierr = m.init(); CHKERRQ(ierr);


    std::unique_ptr<ConstSGivenClimate> climate(new ConstSGivenClimate);
    ConstSGivenClimate *pclimate = climate.get();
    m.attach_sclimate(std::move(climate));

    auto nc(NcFile("bob_pism_forcings.nc"));

    blitz:array<double,1> times;    // Will read these from forcing file
    blitz::Array<double,2> mass_flux, temperature;

    m.set_time(times(0));
    for (int i=0; i<times.size(0)-1; ++i) {
        read_next_record(nc, i, mass_flux, temperature);
        pclimate->set_surface_mass_flux(mass_flux);
        pclimate->set_surface_temperature(temperature);
        ierr = m.run_to(times(i+1)); CHKERRQ(ierr);
    }

```

**Comment by ckhroulev** [comment]
This is ancient and almost certainly no longer relevant. (Coupling is an important topic but PISM's code changed over the last 8 years).
