### ISSUE TITLE
What is a Modifier?

### ISSUE THREAD

**Issue by citibeth** [pism/pism#206]
I'm looking at the template Modifier<Model>.  Documentation is rather sparse, and I have a number of questions:
1. What is a modifer? 
2. What are modifiers used for? 
3. How do they work on the inside?
4. How do modifiers work from the user's point of view?
5. How does the Modifier<Model> template help make modifiers?  
6. Why is Modifier<Model> in the class hierarchy of PSGivenClimate?

**Comment by ckhroulev** [comment]
All questions except for 3 are either

- addressed in the [manual](https://pism-docs.org/sphinx/climate_forcing/index.html#climate-forcing) or
- no longer relevant because of changes in the code.

Please re-open if this issue is still important.
