### ISSUE TITLE
Wiki Docs Revamp

### ISSUE THREAD

**Issue by citibeth** [pism/pism#208]
Documentation on the pism-docs wiki is currently under the "Getting PISM", "Docs" and "Developers" menu.  I understand the logic now, but did not "get it" for too long.  Consider that I first approached the PISM website as follows:
1. Go to "Getting PISM" and follow the instructions.
2. Go to "Docs->Documentation" and "Docs->Quick Installation" and read, and follow the instructions.
3. Ignore most of the rest of the website.  I've already read "Docs->Documentation," what more documentation is there?  One should not be expected to scour every Wiki page to get required information.  the "Developers" menu in particular looks like just a list of the main PISM developers, I never expected key PISM documentation to be sitting there.

I would therefore suggest the following changes:

```
a) Add a text in section 2.2.3 of installation.pdf to tell you to GET THE DEV BRANCH IF YOU THINK YOU'RE GOING TO BE CHANGING THE CODE!!!
```

   b) Under "Getting PISM->Latest release", and "Docs -> Quick Installation" add a section about how to get the development branch (and how you HAVE to do this if you plan on checking in any code).

  c) Move "Docs->Quick Installation" to the top of the menu.  For the impatient...

  d) Move all documentation into "Docs->Documentation" (or into a page linked from there).  This would include stuff currently in: Docs->Quick Installation, Docs->Source Code Browsers, Docs->FAQ, Docs->WhatDoesPISMDo (should be the first thing under Docs->Documentation), Docs->ReportingABug, Developers->DevelopmentVersion, Developers->ComittingToPISM.

   e) Move Developers->OldPISMVersions to the "Getting PISM" menu.

So overall, the main idea of this issue is to move all required documentation into one top-level "Documentation" HTML page.  It should not contain everything, but rather be a higher-level page with links to "chapters" of the documentation.  Headings should include, for example:
1. End-User Documentation
    *) What does PISM Do?
    a) Getting PISM (include Latest Release and Old Versions here.  Some end users will need to run old versions for scientific reasons, that is not just a developers issue).
    b) Optional User Registration
    c) Installation Summary (Quick Installation Guide)
    d) PDF Installation Manual
     e) PDF User Manual
     f) PISM Climate Forcing Components
     *) PISM FAQ
2. Developer Documentation (specify that this should be read AFTER the end-user docs)
    *) First steps (create a GitHub account, etc.)
    a) Getting PISM: Developers Branch.  ("Installing tools and libraries" and "Building the dev version" are not needed, since these are the same as for the prod version).
    b) Git practices: Tracking commits, staying up-to-date, how to create a topical branch, git workflow, etc. This needs a lot of collecting-together and rewriting.
   Other information that needs to go here:
        - How to change the PDF docs (is this something you want to allow?)
        - How to run Doxygen without having set up PISM to compile (I want to run Doxygen on my laptop, where I haven't installed PetSC, etc).

Just a note... the developer's documentation section will need a lot of reworking, and some new material (see my next issue).  I think it might require a couple of iterations.

If you give me permission the Wiki, I'd be happy to take a hack at this.  (Or set up a copy of the Wiki for me to change.  BTW... I really like the github wikis because the Wiki stuff is integrated right in with git.  See, for example:

http://citibob.github.io/glint2/

Maybe there's another way to do a git-integrated Wiki away from github.)

**Comment by ckhroulev** [comment]
PISM's documentation still needs work (and probably always will), but I think this issue need not stay open. Please re-open if you disagree.
