### ISSUE TITLE
Can I change Grid Geometry after call to new IceGrid()...?

### ISSUE THREAD

**Issue by citibob** [pism/pism#220]
I need to make sure that the ice grid GLINT2 sees (see GLINT2 project on github) is the same as the grid PISM sees.  I see two ways to do this:

1. Be very careful about writing PISM's input files so the two grids harmonize

2. Read PISM's input file, and then overwrite with desired grid, immediately after calling "new IceGrid()".

Any thoughts on pros and cons of these approaches?  It seems that (2) would also have to be applied in the spin-up.  Meaning I'd have to make a custom pismr driver for the spinup procedure.

**Comment by ckhroulev** [comment]
As of today the way to ensure that you get the grid you need is this: fill [GridParameters](https://github.com/pism/pism/blob/dev/src/base/util/IceGrid.hh#L73) with desired values and call `new IceGrid(...)`.

An `IceGrid` instance cannot be modified after it is created.
