### ISSUE TITLE
Remove IceEISModel and the pisms executable

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#231]
It should be replaced with a Python script what generates input files and sets configuration parameters and command-line options.

**Comment by ckhroulev** [comment]
Regarding EISMINT II tests "G" and "H": we should not support them.

The `SIA_Sliding` class and the verification test "E" should be removed.

**Comment by bueler** [comment]
I fully agree with your last statement.  I would be delighted if G and H never run again, as long as `-eisII {G,H}` generate an error message and stop.  Test E can die too.  SIA never slides again!

**Comment by aaschwanden** [comment]
I second (third) this.

**Comment by bueler** [comment]
Good news!  Spread it far and wide!

**Comment by ckhroulev** [comment]
I decided to keep `IceEISModel`: it is nice to have a way to create input files for testing using EISMINT-II formulas and *without* extra dependencies like Python.
