### ISSUE TITLE
Hydrology Models: Obtaining lost water

### ISSUE THREAD

**Issue by citibeth** [pism/pism#250]
I'm looking at the latest manual on pism-docs.org.  Section 7.2 describes two hydrology models.  In both cases, I would like to obtain a report on what water is lost, and where it is lost.  I would like this as some PISM variable that I can access in my coupler.
- The mass-conserving "-hydrology routing" model says the amount of water that is lost is reported to the user (p. 56).  How do I obtain this report, both as an end user, and as a coupler author rooting around the PISM code?
- The default "-hydrology null" model also talks about losing water, but does not say how or if that water is reported.  Is there a PISM variable I can go to in order to get this lost water?  If not, how would I modify PISM to make it report this lost water?  [It looks like I'd want to modify the line:

`Wtil(i,j) = PetscMin(PetscMax(0.0, Wtil(i,j)), tillwat_max);`
to look like:

```
} else {
    Wtil0_ij = Wtil(i,j)
    Wtil(i,j) += icedt * (total_input(i,j) - C);
    Wtil(i,j) = PetscMin(PetscMax(0.0, Wtil(i,j)), tillwat_max);
    delta_wtil = Wtil(i,j) - Wtil0_ij
```

Now would detla_wtil have the lost water for gridcell (i,j)?  If so, the thing I'd need help with is stuffing it into a IceModelVec of one sort or another (and allocating that IceModelVec variable).

---

I see in hydrology_diagnostics.cc: "hydroinput" and "bwat".  Would it be possible to get water output from this?  For example, could I solve for hydrooutput in:

   \int_{time} hydroinput dt + bwat ==? \int_{time} hydrooutput

**Comment by ckhroulev** [comment]
I realize that this issue contains many questions that are still unanswered, but here's a comment addressing the title, i.e. keeping track of lost water: in the current "developmental" code all hydrology models provide all the fields needed to "balance the books". See [the manual](https://github.com/pism/pism/blob/506aea41f/doc/sphinx/manual/practical-usage/mass-conservation.rst#L102) for a way to get rates of change of the mass of subglacial water and these `Hydrology` methods to get corresponding changes over one time step:

```
  const IceModelVec2S& mass_change() const;
  const IceModelVec2S& mass_change_at_grounded_margin() const;
  const IceModelVec2S& mass_change_at_grounding_line() const;
  const IceModelVec2S& mass_change_at_domain_boundary() const;
  const IceModelVec2S& mass_change_due_to_conservation_error() const;
  const IceModelVec2S& mass_change_due_to_input() const;
  const IceModelVec2S& mass_change_due_to_lateral_flow() const;
```

Please re-open if this is still relevant and/or if you need more info.
