### ISSUE TITLE
Implement PDD temperature standard deviation parametrization

### ISSUE THREAD

**Issue by juseg** [pism/pism#265]
According to atmospheric reanalysis of near-surface temperature data, there exist a correlation between standard deviation and mean of temperature over the Greenland ice sheet. I want to implement this as a parametrization of PDD standard deviation in the form _Sigma = a.T + b_ over ice-covered grid cells.

**Comment by ckhroulev** [comment]
Deleted branch pdd-stdev (was c98c555).
