### ISSUE TITLE
Verify that Top Neumann Boundary Condition change is benign

### ISSUE THREAD

**Issue by citibob** [pism/pism#274]
Need to:

1. Find an existing test.

2. Run it with Dirichlet BC with old and new code.  Answers should be exactly the same.

**Comment by ckhroulev** [comment]
If I remember correctly the top-surface Neumann B.C. is not used in coupling PISM to GLINT2 any more.

@citibob : please correct me if I'm wrong (and re-open this issue if necessary).

**Comment by citibob** [comment]
Yes, that is correct.
