### ISSUE TITLE
Test Correctness of Top Neumann Boundary Condition

### ISSUE THREAD

**Issue by citibeth** [pism/pism#275]
Need to go in with a microscope and the heat equation.  Test that (for example):

1. Heat flows specified by the Neumann BC are reflected in the total enthalpy of the column.

See if it is practical to run just the 1-D heat equation portion of PISM, standalone.

**Comment by ckhroulev** [comment]
If I remember correctly the top-surface Neumann B.C. is not used in coupling PISM to GLINT2 any more.

@citibob : please correct me if I'm wrong (and re-open this issue if necessary).

**Comment by ckhroulev** [comment]
See the branch [`ckhroulev/top-surface-neumann`](https://github.com/pism/pism/tree/ckhroulev/top-surface-neumann) for an [implementation of the Neumann B.C. at the top surface](https://github.com/pism/pism/blob/ckhroulev/top-surface-neumann/src/base/energy/enthSystem.cc#L197) of the ice and [`test/enthalpy.py`](https://github.com/pism/pism/blob/ckhroulev/top-surface-neumann/test/enthalpy.py) for a very basic (and unfinished) verification test setup.

I am certain that this code can be merged into `dev` right now (the top surface equation corresponding to the Dirichlet case is exactly the same as before, so this does not affect any modeling results -- so far), but we don't need to merge it yet.

What we do need is an exact solution of an IBVP for the 1D heat equation with Dirichlet B.C. at one end and Neumann at the other. (Looking at Ed's test K preprint might be useful, although not necessary: this is a textbook problem, after all.)

**Comment by ckhroulev** [comment]
Here's why I think it's time to merge `ckhroulev/top-surface-neumann` into `dev` and close this issue:

* The document [`src/base/energy/doc/discretization.tex`](https://github.com/pism/pism/blob/021ce59df5c628ab3e35e0e229eb4dbcbee936ec/src/base/energy/doc/discretization.tex) now fully describes the derivation of the FD discretization used to solve the enthalpy system in the column, including boundary conditions.

* The script [`test/enthalpy.py`](https://github.com/pism/pism/blob/021ce59df5c628ab3e35e0e229eb4dbcbee936ec/test/enthalpy.py) now evaluates PISM's implementation of the approximation of the enthalpy system using exact solutions of two IBVPs:

  - constant-coefficient time-dependent diffusion in the column with Neumann BC at one boundary and Dirichlet at the other (zero advective and source terms)
  - constant-coefficient time-dependent advection with Neumann BC at the in-flow boundary (zero diffusion and source terms)

The exact solution of the diffusion problem is documented in [`src/base/energy/doc/exact/diffusion.tex`](https://github.com/pism/pism/blob/021ce59df5c628ab3e35e0e229eb4dbcbee936ec/src/base/energy/doc/exact/diffusion.tex). The exact solution for the advection problem is simpler, so the Maxima script [`src/base/energy/doc/exact/advection.mac`](https://github.com/pism/pism/blob/021ce59df5c628ab3e35e0e229eb4dbcbee936ec/src/base/energy/doc/exact/advection.mac) is enough.

I believe that these exact solutions are sufficient to ensure that our implementation of boundary conditions is correct, but they do **not** test configurations that include temperate ice, or depth-dependent thermal conductivity, or PISM's code deciding which boundary condition to use, or...

Here are plots produced by `test/enthalpy.py`, just for the record.

![diffusion-dirichlet-neumann-space](https://cloud.githubusercontent.com/assets/1018111/12317357/10e0c952-ba3d-11e5-8aee-482bb7a7bb4b.png)
![diffusion-dirichlet-neumann-time](https://cloud.githubusercontent.com/assets/1018111/12317356/10de3f7a-ba3d-11e5-831e-b28c0086e9cf.png)
![diffusion-neumann-dirichlet-space](https://cloud.githubusercontent.com/assets/1018111/12317358/10e22e78-ba3d-11e5-9d4b-d4e538803038.png)
![diffusion-neumann-dirichlet-time](https://cloud.githubusercontent.com/assets/1018111/12317359/10e5206a-ba3d-11e5-8bac-19589dfdd6cb.png)

![advection-down-space](https://cloud.githubusercontent.com/assets/1018111/12317365/194e3b42-ba3d-11e5-9ff4-e75f1f3e3824.png)
![advection-down-time](https://cloud.githubusercontent.com/assets/1018111/12317364/194e439e-ba3d-11e5-9608-560db44ec8ef.png)
![advection-up-space](https://cloud.githubusercontent.com/assets/1018111/12317363/194dbf28-ba3d-11e5-9dfa-82a80c0f35d5.png)
![advection-up-time](https://cloud.githubusercontent.com/assets/1018111/12317366/194e47cc-ba3d-11e5-9765-dd3d4ae3aaea.png)

**Comment by bueler** [comment]
I was too sleepy last night to say this:  It does look good to me!
