### ISSUE TITLE
Merge GLINT2EnthalpyConverter into PISM codebase

### ISSUE THREAD

**Issue by citibob** [pism/pism#276]
Prerequesite:
   https://github.com/pism/pism/issues/273

Once the prerequisite is finished, need to:

1. Add documentation to the code:
  a) What functions (i.e. H(T,omega,p),  T(H,p), omega(H,p)) are they computing? 
  b) What is the justification (i.e. citation or analysis) for these new functions?  (Kirchoff's Relation of Thermodynamics)

2. Make sure it is possible to run with EnthalpyConverter as specified in Aschwanden et al (2012).

3. Submit for merging into dev

**Comment by ckhroulev** [comment]
Done now that `pism::KirchhoffEnthalpyConverter` is implemented and tested.

**Comment by citibob** [comment]
Constantine,

A big thanks!

Bob
