### ISSUE TITLE
regridding to finer grid & age computation

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#307]
During a standard paleo spinup with grid refinement (and age computation) I get:

```
regridding 3D variables from file g9000m_m5ka_paleo_970mW_hs.nc ...
PISM ERROR: some values of 'age' are less than the valid minimum (0.000000 s).
            Please inspect variable 'age' in 'g9000m_m5ka_paleo_970mW_hs.nc' and replace offending entries.
            PISM will stop now.
*** The MPI_Barrier() function was called after MPI_FINALIZE was invoked.
```

Assume we have a multi-stage spinup:

      a    b    c  
    A -> B -> C ->

This happens when regridding from C only and only if a and b are different grid resolutions. That is, the same script (incl. all regridding commands) works fine if a and b are the same grid resolutions.
I have slow internet at home so I'll provide further information a bit later.

**Comment by ckhroulev** [comment]
PISM's error message was correct: some values of '`age`' were less than the valid minimum.

So far we fix this by [setting negative age to zero](https://github.com/pism/pism/blob/stable0.7/src/base/iMage.cc#L307).
