### ISSUE TITLE
Proposal: replace "-boot_file file.nc" with "-i file.nc -bootstrap"

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#308]
@aaschwanden, @bueler: What do you think about this?

I believe that this would make the code simpler because `-i` would always give the name of the input file. (I also prefer the way it looks.)

**Comment by bueler** [comment]
The only difficulty, which should not be regarded as disabling this idea, is that the user may be less aware that heuristics are being used to fill in stuff.  How will users know?

**Comment by ckhroulev** [comment]
> the user may be less aware that heuristics are being used to fill in stuff.

Could you please elaborate on this?

To spell out what I am proposing:

 * Always use `-i` to specify the input file and remove `-boot_file`.
 * Add the option `-bootstrap`, meaning "treat the input file as the file to bootstrap from".

With these changes `-i` alone has the same meaning as before and `-i file.nc -bootstrap` has the same meaning as (current) `-boot_file file.nc`.

It seems to me that this does not change the user's ability to see what heuristics are used (but I'm not a normal user, so I can't predict how others understand this).

**Comment by bueler** [comment]
_Love_ it.

Sorry, my first response came from mis-reading the message as using only "-i" for all input files.  I missed the actual issue name, which includes the flag `-bootstrap`.

**Comment by aaschwanden** [comment]
Sounds good to me.
