### ISSUE TITLE
Proposal: rename NetCDF variable "mask" to "ice_mask"

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#309]
I think it would be good to use a name that is more specific than the current one ("mask"): future sub-models of PISM might use other masks and we want to be able to distinguish them easily.

PS: "ice_mask" is the name already used in David's Python code.

**Comment by bueler** [comment]
Sounds good to me.

**Comment by aaschwanden** [comment]
Hm, let me think about this.

When I read "ice_mask" I think of a binary mask where 0 = ice and 1 = no
ice (or vice versa).

**Comment by ckhroulev** [comment]
Please re-open if you think that this is still relevant.
