### ISSUE TITLE
Atmosphere lapse rate with surface PDD model SEGV 

### ISSUE THREAD

**Issue by jsegu** [pism/pism#315]
Tested on PISM dev d550c89 from March 11, 2015.

The issue can be easily reproducible by adding a PDD model to the `atmosphere_given_lapse_rate` test in https://github.com/pism/boundary-tests (I can push that new test from my computer if you add boundary-tests in the list of the PISM team repo).

After realizing that my current set-up do not work with newer dev versions, this issue was quite hard to diagnose due to the lack of error message. I could gather quite a bit of information on the problem but I could not identify the cause.

First PISM's standard output ends at:

    getting surface B.C. from couplers...
      FOUND  usurf / standard_name=surface_altitude
                   \ min,max =     0.000,  500.000 (m)

Then the standard error:

    [0]PETSC ERROR: ------------------------------------------------------------------------
    [0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
    [0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
    [0]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
    [0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
    [0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
    [0]PETSC ERROR: to get more information on the crash.
    [0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
    [0]PETSC ERROR: Signal received
    [0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
    [0]PETSC ERROR: Petsc Release Version 3.5.3, Jan, 31, 2015 
    [0]PETSC ERROR: pismr on a linux-gnu-opt named ogive by juliens Tue Apr 21 17:14:04 2015
    [0]PETSC ERROR: Configure options --prefix=/scratch_net/ogive/juliens/software/opt/petsc-3.5.3 --with-petsc-arch=linux-gnu-opt --with-shared-libraries --with-debugging=0 --with-fortran=0
    [0]PETSC ERROR: #1 User provided function() line 0 in  unknown file
    --------------------------------------------------------------------------
    MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
    with errorcode 59.
    
    NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
    You may or may not see output from other processes, depending on
    exactly when Open MPI kills them.
    --------------------------------------------------------------------------

Without any experience I also tried to use valgrind, which certainly gives a hint on the problem.

    ==30450== Memcheck, a memory error detector
    ==30450== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
    ==30450== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
    ==30450== Command: /home/julien/opt/pism-dev-150219-ed83be2-debug/bin/pismr -verbose 5 -boot_file boot.nc -o out.nc -y 10000 -Mx 75 -My 150 -Mz 26 -Lz 5000 -Mbz 16 -Lbz 3000 -atmosphere given,lapse_rate -atmosphere_given_file atm.nc -atmosphere_given_period 1 -temp_lapse_rate 6.0 -atmosphere_lapse_rate_file test.nc -timestep_hit_multiples 1 -surface pdd -malloc_debug
    ==30450== Parent PID: 30446
    ==30450== 
    ==30450== Invalid read of size 8
    ==30450==    at 0x5460D60: pism::atmosphere::LapseRates::begin_pointwise_access() (PALapseRates.cc:88)
    ==30450==    by 0x54A975B: pism::surface::TemperatureIndex::update_impl(double, double) (PSTemperatureIndex.cc:319)
    ==30450==    by 0x5C96BEC: pism::Component_TS::update(double, double) (PISMComponent.cc:168)
    ==30450==    by 0x4EE6B45: pism::IceModel::init_step_couplers() (iMinit.cc:806)
    ==30450==    by 0x4ECFE4B: pism::IceModel::bootstrapFromFile(std::string const&) (iMbootstrap.cc:104)
    ==30450==    by 0x4EE5507: pism::IceModel::set_vars_from_options() (iMinit.cc:568)
    ==30450==    by 0x4EE3C12: pism::IceModel::model_state_setup() (iMinit.cc:389)
    ==30450==    by 0x4F2092C: pism::IceModel::init() (iceModel.cc:936)
    ==30450==    by 0x402C65: main (pismr.cc:90)
    ==30450==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
    ==30450== 
    ==30450== 
    ==30450== HEAP SUMMARY:
    ==30450==     in use at exit: 51,812,113 bytes in 34,735 blocks
    ==30450==   total heap usage: 154,728 allocs, 119,993 frees, 983,131,293 bytes allocated
    ==30450== 
    ==30450== LEAK SUMMARY:
    ==30450==    definitely lost: 694 bytes in 9 blocks
    ==30450==    indirectly lost: 70 bytes in 3 blocks
    ==30450==      possibly lost: 164,987 bytes in 3,714 blocks
    ==30450==    still reachable: 51,646,362 bytes in 31,009 blocks
    ==30450==         suppressed: 0 bytes in 0 blocks
    ==30450== Rerun with --leak-check=full to see details of leaked memory
    ==30450== 
    ==30450== For counts of detected and suppressed errors, rerun with: -v
    ==30450== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

Last but not least, I also identified the problematic commit a02c64a. The SEGV does not occur in the previous version 8074d9a. This is actually how I came to realize the issue had something to do with lapse rates.

P.S. I could not reproduce this on the latest dev version (57ab6ed from yesterday April 20, 2015), because PISM then crashes even earlier with a segmentation fault (work in progress I assume).

**Comment by ckhroulev** [comment]
Thanks for the report! I'll look into this right now.

**Comment by ckhroulev** [comment]
@jsegu: Please give it a try and close this issue if it is resolved now.

**Comment by jsegu** [comment]
@ckhroulev This was fast! As far as I can tell things run smoothly now. Many thanks for the bug fix (and adding an extra test in boundary-tests)!
