### ISSUE TITLE
Clean up PISM branches on GitHub

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#317]
Here's the list of old branches:

- `dev_glbug_solved` (was d506204, Tue Nov 27 2012).
- `inv_hardness` (was 89b6d69, Sun Jun 2 2013).
- `ocean_kill_flux_2D` (was 99b69b7, Tue Oct 16 2012).
- `pdd-stdev` (was c98c555, Tue Apr 15 2014).
- `pik` (was c0fd713, Thu May 29 2014).
- `storglaciaren` (was e902cfd, Mon Jun 18 2012).
- `tikhonov` (was c31711b, Thu Sep 13 2012).
- `using-c++11-features` (was 510d930, Fri Nov 15 2013).
- `pdd-refreeze-stdev` (was 0574607, Thu Sep 26 2013).
- `pik_fracdens` (was 18b2f1f, Wed Oct 2 2013).
- `pik_master` (was d591e97, Wed Jun 20 2012).
- `pik_ocean_diag` (was 6e80072, Tue Nov 6 2012).
- `pik_stable_0a` (was 315e1ef, Wed Apr 11 2012).

Git branches are just "tags", so we can re-create them if needed.

**Comment by ckhroulev** [comment]
I created this issue to document what was already done. Please re-open if you need to re-create a branch (or just use the SHA-1 hash to re-create it yourself.)

**Comment by JohannesFeldmann** [comment]
About half of the branches were created from our (PIK) side and kind of orphaned since months anyway. So thanks for the clean up!
