### ISSUE TITLE
fix EISMINT II settings so v0.7 conforms

### ISSUE THREAD

**Issue by bueler** [pism/pism#323]
Thomas Kleiner wrote an email (below).  This is first a grid-periodicity issue (re dx and dy) and a documentation issue (re Lz) and a default flags error (re flow law).

And it is a good exercise for bueler ...

```
after compiling the new stable 0.7 version of PISM, I found that the
Eismint II experiment A is not running on the expected grid resolution 
of 25km for the default grid (-Mx 61 -My 61):

$ pisms -eisII A 
PISMS stable v0.7-5-g3d3f708 (simplified geometry mode)
...
computational domain and grid:
                grid size   61 x 61 x 31
           spatial domain   1500.00 km x 1500.00 km x 4000.00 m
     horizontal grid cell   24.59 km x 24.59 km
  vertical spacing in ice   uneven, 31 levels, 36.667 m < dz < 230.000 m

Similar for the 10km grid (-Mx 151 -My 151).

Further, the default setting for the vertical extend of the grid (4000m) is
not sufficient for longer runs than approx 8000 years:

$ pisms -eisII A -y 9000  
...
$v$Eh  diffusivity (overrides 2D CFL) (dt=3.63717)
S 00008091.298:    2.14840    0.88283          0.63219    112.14769
PISM ERROR: Max ice thickness (4000.0645 m) exceeds the height of the computational box (4000.0000 m).

I am not sure, if the correct flow law is used internally. According to Eismint II
(Payne et al., 2000), the flow law should be Glen-Paterson-Budd but PISM
reports a Glen-Paterson-Budd-Lliboutry-Duval flow law. 

I found
    m_config->set_boolean("do_cold_ice_methods", true);
in pism0.7/src/eismint/iceEISModel.cc. Is this Glen-Paterson-Budd?

$ pisms -eisII A 
...
* Initializing the SIA stress balance modifier...
  [using the Glen-Paterson-Budd-Lliboutry-Duval flow law]
...
```

**Comment by bueler** [comment]
@ckhroulev  I have now pushed (cherry-picked) the fix to stable0.7 and dev branches.   But test_08.sh now fails for me (`regridding:vertical_direction:test_08.sh`).  I think this is because the grid periodicity on pisms changed, but it could be the change to Paterson-Budd.  I do not understand the current regression test setup well enough to fix it myself, so I appreciate help on this too.

**Comment by ckhroulev** [comment]
Yes, that is periodicity. I just pushed a fix to both `dev` and `stable0.7`.

A side note: "pb" and "gpbld" flow laws are equivalent (and even use the same code) for cold ice.

**Comment by bueler** [comment]
> A side note: "pb" and "gpbld" flow laws are equivalent (and even use the same code) for cold ice.

Right.  I'll leave it as is for superficial conformity to EISMINT II specs.

**Comment by bueler** [comment]
I am closing this because I don't think Thomas is on github to do it himself.  I'll reopen if he reports ongoing issues.
