### ISSUE TITLE
small bug in -save_file option

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#325]
pismr -i result_nomass_equi_20km.nc -surface pik -ocean pik -bed_def none -calving eigen_calving,thickness_calving -eigen_calving_K 1.0e17 -thickness_calving_threshold 100.0 -ys -50000 -ye 0 -skip -skip_max 5 -options_left -verbose 3 -o_order zyx -backup_interval 0.5 -sia_e 4.5 -ssa_e 0.512 -ssa_method fd -stress_balance ssa+sia -pik -topg_to_phi 5.0,20.0,-1000.0,0.0 -subgl -subgl_type LI -energy cold -tauc_slippery_grounding_lines -o result_equi_20km_50000yrs.nc -o_size big
-save_file snap_equi_20km_50000yrs.nc -save_times -50000:5000:0 -save_split -save_size medium

It does not seem to be an issue of -save_split nor of -save_size...

This is the last snippet of the output....
...
y  SSA: ... =  104 outer iterations, ~15.5 KSP iterations each
v$Eh  3D CFL (dt=0.00170)
S -0049999.998:   26.22401   13.62360         14.69372 11225815.76044

saving snapshot to snap_equi_20km_50000yrs.nc--0049999.998.nc at -0049999.998, for time-step goal -0050000.000

  Writing bheatflx...
  Writing bmelt...
  Writing dbdt...
  Writing enthalpy...
  Writing temp...
  Writing litho_temp...
  Writing tillwat...
  Writing ice_surface_temp...
  Writing climatic_mass_balance...
  Writing tmp...
  Writing tmp...
  Writing bwat...
  Writing diffusivity...
  Writing velbar_mag...
  Writing liqfrac...
  Writing schoofs_theta...
  Writing taub_mag...
  Writing taud_mag...
  Writing temp_pa...
  Writing topgsmooth...
  Writing velbar_mag...
  Writing velbase_mag...
  Writing velsurf_mag...
  Writing wvelsurf...
PISM WARNING: the following variables were *not* written by PISM core (IceModel): IcebergMask bwatvel climatic_mass_balance edot_1 edot_2 ice_surface_temp litho_temp shelfbmassflux shelfbtemp tillphi tillwat topg_initial vel_ssa
pismr: ncx.c:2059: ncx_put_size_t: Assertion `*ulp <= 4294967295U' failed.

**Comment by ckhroulev** [comment]
1.  What is the PISM version you are using?
2.  Can you try to eliminate irrelevant options from the command, please?
3.  I see `pismr: ncx.c:2059: ncx_put_size_t: Assertion ``*ulp <= 4294967295U' failed` at the bottom of the output you included. Is this the issue you are referring to? (This is not clear from the message above.)

(Please keep [these guidelines](http://pism-docs.org/wiki/doku.php?id=reporting_bugs) in mind so that I don't have to repeat them every time.)

**Comment by talbrecht** [comment]
Sorry Constantine for that lousy bug description, fortunately it has been quite a while since the last bug report from my side. I immediately bookmarked the guidelines...

I have been using PISMR stable v0.7-2-g1e388f6 (basic evolution run mode) and as input the pism_Antarctica_5km.nc generated in the the searise_antarctica example.

pismr -bootstrap -i pism_Antarctica_5km.nc -Mx 120 -My 120 -Lz 5000 -Lbz 2000 -Mz 31 -Mbz 10 -atmosphere given -surface simple  -y 200 -o result_boot_50km.nc
-save_file snap_boot_equi_50km.nc -save_times 0:1:200

The run breaks when saving the snapshot to file, so -save_file is the critical option...

The last output statement before it breaks is:
....
saving snapshot to /scratch/01/albrecht/pism15/pismOut/paleo_antarctica/testbug/results/snap_boot_equi_50km.nc at 00000005.328, for time-step goal 00000000.000

pismr: ncx.c:2059: ncx_put_size_t: Assertion `*ulp <= 4294967295U' failed.

Yes, this last line is the issue I am referring to. The list of vars for printout does not seem complete in iMIO.cc..

**Comment by ckhroulev** [comment]
@talbrecht : Thanks for the bug report! I think this bug should be fixed in `stable0.7` and `dev` now. Please re-open this issue if it is still a problem.
