### ISSUE TITLE
Issues with time bounds and CDO

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#327]
There appears to be a subtle bug/feature in the way PISM writes the time bounds for a hindcast. Please see discussion on the CDO bug tracker:

https://code.zmaw.de/issues/6027

Note that CDO works fine on files that are in "days since....", so I'm wondering if a slight hick-up of 1s in the calendar calculation can cause the shift outlined by Uwe.

**Comment by bueler** [comment]
Does CDO _really_ have an issue tracker behind password protection?  If you created the issue, can you repost it here?

**Comment by aaschwanden** [comment]
Didn't realize one needs to have an account on the CDO tracker to see issues.  Will repost the conversation tomorrow.

**Comment by aaschwanden** [comment]
It seems to be the easiest to attach a screen shot of the conversation with Uwe on the CDO bug tracker.
The files can be found here: https://www.dropbox.com/s/mwh92al22nth5r7/cdo-time-bounds.zip?dl=0

![cdo](https://cloud.githubusercontent.com/assets/120698/9265287/a827e490-41dd-11e5-9f2f-7431a3283764.png)

**Comment by ckhroulev** [comment]
Done in the `dev` branch and will be a part of the next release.
