### ISSUE TITLE
sug_gl calculation is not symmetric since stable0.6

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#331]
I have just noticed that (since stable0.6) in IceModel::update_floatation_mask() of iMgeometry.cc you have inserted else-if-conditions for the four grid directions (in both the floating and the grounded part):

if (mask.ocean(i + 1, j)) {
} else if (mask.ocean(i - 1, j)) {
} else if (mask.ocean(i, j + 1)) {
} else if (mask.ocean(i, j - 1)) {

This should be changed into just independent if-conditions (as we had in stable0.5), since the contributions of all four cases is summed up in the end... 

if (mask.ocean(i + 1, j)) {}
if (mask.ocean(i - 1, j)) {}
if (mask.ocean(i, j + 1)) {}
if (mask.ocean(i, j - 1)) {}

and the same for the grounded part. I cannot say yet, how big the impact of this modification is, but since grounding line interpolation is used per default, it should be corrected for, also in the stable branches?! Let me know, what I can do.

**Comment by talbrecht** [comment]
And we should introduce some kind of minimal value for the gl_mask for the grounded part (e.g. 0.1) and eventually a maximum value for the floating part (e.g. 0.9) to avoid convergence problems?!

**Comment by ckhroulev** [comment]
On Nov 26, 2015 @talbrecht wrote:

> And we should introduce some kind of minimal value for the gl_mask for the grounded part (e.g. 0.1) and eventually a maximum value for the floating part (e.g. 0.9) to avoid convergence problems?!

I don't know what convergence problems this is referring to, so I can't say that I agree -- or disagree. I am reluctant to add such limits to `gl_mask` itself, though: most likely it is better to modify the code that uses `gl_mask` instead.

Please submit a bug report or open an issue if necessary. (Please don't forget to provide [the information we need to diagnose and fix a bug](http://pism-docs.org/wiki/doku.php?id=reporting_bugs).)
