### ISSUE TITLE
Ensure that PISM output is ready for ISMIP6

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#332]
See [A2.3 Model output variables and README file](http://www.climate-cryosphere.org/wiki/index.php?title=InitMIP#A2.3_Model_output_variables_and_README_file) for the list of variables, standard names, etc.

**Comment by aaschwanden** [comment]
I think this is a good idea, PISM should be as compliant as possible with widely accepted standards. Currently the meaning of several variables listed in http://www.climate-cryosphere.org/wiki/index.php?title=InitMIP#A2.3_Model_output_variables_and_README_file require clarification. This discussion is planned for the initMIP pre-AGU 2015 meeting. No action should be taken until the ISMIP6 community ratifies the suggested format.

**Comment by ckhroulev** [comment]
Specifically: implement

- [ ] `land_ice_area_fraction`
- [ ] `grounded_ice_sheet_area_fraction`
- [ ] `floating_ice_sheet_area_fraction`

Note that not all "standard names" listed in appendix A2.3 are standard according to the [CF Standard name table](http://cfconventions.org/Data/cf-standard-names/30/build/cf-standard-name-table.html).

**Comment by ckhroulev** [comment]
Regarding fluxes such as the 2D surface and basal mass flux and their totals reported as scalars: we need to know if the 2D fields are reported for the whole computational domain or only for the ice-covered area, and whether scalar totals are to be obtained by integrating over the whole domain or not.

**Comment by ckhroulev** [comment]
More on fluxes: the sign convention (such as "positive means ice gain") is not specified.

**Comment by ckhroulev** [comment]
I think I need to implement `upward_geothermal_heat_flux_at_ground_level`. This is PISM's `bheatflx` when `Mbz==1`. As far as I can tell PISM computes but cannot report the heat flux from the bedrock into the ice with `Mbz > 1`.

**Comment by ckhroulev** [comment]
The InitMIP document (see the link above) misspells one of the variable names: **Grounded ice sheet area fraction** should be `sftgrf`, not `sfrgrf`.

The current spelling makes it inconsistent with the [ISMIP6](http://clipc-services.ceda.ac.uk/dreq/u/ISMIP6.html) document, and following existing conventions is the only reason to use such monstrosity, as far as I can tell.

**Comment by ckhroulev** [comment]
List of InitMIP requested variables whose "standard name" is not in the [CF standard names table](http://cfconventions.org/Data/cf-standard-names/30/build/cf-standard-name-table.html) or on the list of [proposed CF standard names](http://cfeditor.ceda.ac.uk/proposals/1?status=active&namefilter=ice&proposerfilter=&descfilter=&unitfilter=&yearfilter=&commentfilter=&filter+and+display=Filter).

Variable name | Description | Units | InitMIP "standard" name
--- | --- | --- | ---
hfgeoubed | Geothermal heat flux | W m-2 | upward_geothermal_heat_flux_at_ground_level
libmassbf | Basal mass balance flux | kg m-2 s-1 | land_ice_basal_specific_mass_balance_flux
licalvf | Calving flux | kg m-2 s-1 | land_ice_specific_mass_flux_due_to_calving
litempbot | Basal temperature | K | land_ice_basal_temperature
litempsnic | Surface temperature | K | temperature_at_ground_level_in_snow_or_firn
sfrgrf | Grounded ice sheet area fraction | 1 | grounded_ice_sheet_area_fraction
sftflf | Floating ice sheet area fraction | 1 | floating_ice_sheet_area_fraction
strbasemag | Basal drag | Pa | magnitude_of_land_ice_basal_drag
uvelsurf | Surface velocity in x | m s-1 | land_ice_surface_x_velocity
vvelsurf | Surface velocity in y | m s-1 | land_ice_surface_y_velocity
wvelbase | Basal velocity in z | m s-1 | land_ice_basal_upward_velocity
wvelsurf | Surface velocity in z | m s-1 | land_ice_surface_upward_velocity
lim | Total ice mass | kg | land_ice_mass
limnsw | Mass above floatation | kg | land_ice_mass_not_displacing_sea_water
iareag | Grounded ice area | m2 | grounded_land_ice_area
iareaf | Floating ice area | m2 | floating_ice_shelf_area *(was floating_land_ice_area)*
tendacabf | Total SMB flux | kg s-1 | tendency_of_land_ice_mass_due_to_surface_mass_balance
tendlibmassbf | Total BMB flux | kg s-1 | tendency_of_land_ice_mass_due_to_basal_mass_balance
tendlicalvf | Total calving flux | kg s-1 | tendency_of_land_ice_mass_due_to_calving

**Comment by ckhroulev** [comment]
The INITMIP6 document requests reporting every year (scalars) and every five years (2D fields) but does not specify the meaning of "year" or the format of the time axis (such as time units) in model output files.

**Comment by florianziemen** [comment]
And I'm very happy about that. One more DOF for me. ;)

**Comment by talbrecht** [comment]
Thanks for preparing PISM for initMIP. I just wonder if I got all the output variables for Antarctica right according to the list in the[ Wiki](http://www.climate-cryosphere.org/wiki/index.php?title=InitMIP-Antarctica):

**scalars requested (variable name):**  lim, limnsw, iareag, iareaf, tendacabf, tendlibmassbf, tendlicalvf, tendligroundf

PISM: `ts_vars="mass_glacierized,limnsw,area_glacierized_grounded,area_glacierized_shelf,surface_ice_flux,grounded_basal_ice_flux,sub_shelf_ice_flux,H_to_Href_flux,discharge_flux"`

Can the total SMB be calculated as sum of `sub_shelf_ice_flux` and `grounded_basal_ice_flux`? And can H_to_Href_flux be interpreted as calving flux? Does 'land ice mass' include the ice shelves as in `mass_glacierized`?

**2D fields requested (standard names)**: land_ice_thickness, surface_altitude, base_altitude, bedrock_altitude, tendency_of_land_ice_thickness, upward_geothermal_heat_flux_at_ground_level,
land_ice_surface_specific_mass_balance_flux, land_ice_basal_specific_mass_balance_flux,  
land_ice_surface_x_velocity, land_ice_surface_y_velocity, land_ice_surface_upward_velocity, 
land_ice_basal_x_velocity, land_ice_basal_y_velocity, land_ice_basal_upward_velocity, 
land_ice_vertical_mean_x_velocity, land_ice_vertical_mean_y_velocity, 
temperature_at_ground_level_in_snow_or_firn, land_ice_basal_temperature, 
magnitude_of_land_ice_basal_drag, land_ice_specific_mass_flux_due_to_calving, land_ice_specific_mass_flux_due_at_grounding_line, 
land_ice_area_fraction, grounded_ice_sheet_area_fraction, floating_ice_sheet_area_fraction

PISM: `extra_vars="thk,usurf,topg,hfgeoubed,surface_mass_balance_average,basal_mass_balance_average,dHdt,velbar,velbase,velsurf,wvelsurf,wvelbase,tempbase,tempsurf,taub_mag,sftgif,sftgrf,sftflf"`

OK, the variable `base` can be easily calculated from` usurf `and` thk`. And then there is calving flux `licalvf` and the grounding line flux `ligroundf`, which are both no PISM output variables yet, right?

**Comment by aaschwanden** [comment]
Interestingly, I never heard of ‘base_altitude’  and ‘land_ice_specific_mass_flux_due_at_grounding_line’ before—it is not requested for initMIP-Greenland.

‘licalvf’ is ‘discharge_flux’ (which is currently broken in dev, we’re working on it), see https://github.com/pism/pism-gris/blob/master/resources/ismip6vars.csv.

@ckhroulev: with the new mass transport scheme, could we compute ‘land_ice_specific_mass_flux_due_at_grounding_line’?

**Comment by ckhroulev** [comment]
As far as I know all necessary changes (`land_ice_specific_mass_flux_due_at_grounding_line` included) are implemented in the `dev` branch and so will be in the next release.
