### ISSUE TITLE
Replace pism::EnthalpyConverter with pism::KirchhoffEnthalpyConverter

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#334]
As described [in the PISM source code browser](http://www.pism-docs.org/doxy/html/classpism_1_1KirchhoffEnthalpyConverter.html#details) we now know that `dH/dp = 0` together with `c_i = constant` and `c_w = constant` require

![l](https://cloud.githubusercontent.com/assets/1018111/11765936/a978422a-a11b-11e5-8f81-2d4d921b7cba.png)

I. e. a consistent interpretation of the paper *An enthalpy formulation for glaciers and ice sheets* by @aaschwanden  et al has to have `L` (the latent heat of fusion) of the form stated above, i.e. the form that follows from Kirchhoff's law of thermochemistry.

I think PISM should use this form by default. What do *you* think?

**Comment by bueler** [comment]
My lack of objection is not based on much knowledge.

**Comment by citibob** [comment]
I'm not sure of the question.  If the issue is over which converter is used
by default, I have no opinion.  I'm glad the kirchoff converter made it in.

Bob

**Comment by ckhroulev** [comment]
> I'm not sure of the question.

I'm leaning towards using `L = L(p)` (the Kirchhoff relation) in the default enthalpy converter and removing other enthalpy converters. The question is this: are there any objections?

**Comment by ckhroulev** [comment]
This change is implemented in the current `dev` branch. The old behavior is easy to restore: we just need to set `m_c_w = m_c_i` (*specific heat capacity of pure water = specific heat capacity of ice*) in `EnthalpyConverter`.

Please re-open this issue if the new behavior becomes an issue.
