### ISSUE TITLE
Check CMAKE version once in the project

### ISSUE THREAD

**Issue by citibeth** [pism/pism#337]
Currently we have the following inconsistent state:

```
../CMake/PISM_CMake_macros.cmake:  if (${CMAKE_VERSION} VERSION_LESS "2.8.5")
../CMakeLists.txt:if (NOT ${CMAKE_VERSION} VERSION_LESS 3.0.0)
../CMakeLists.txt:  message(STATUS "CMAKE_VERSION >= 3.0.0. Setting policy 0026 behavior to 'old'...")
```

**Comment by ckhroulev** [comment]
I think this is addressed now (by e2bf5f7987d9ae9e19436207a91d4ec566b4a4dc).

I want to support older versions of CMake (no older than 2.8.8, though) as well as CMake 3.0 and newer, so I don't think the rest of the checks can be removed. Comments are welcome, though.
