### ISSUE TITLE
Proposal: Make exceptions optional

### ISSUE THREAD

**Issue by citibeth** [pism/pism#338]
I would like to replace code like:
```
throw RuntimeError::formatted("Error in %s", my_string.c_str())
```
with:
```
(*pism_error)("Error in %s", my_string.c_str())
```
...where pism_error is a function pointer defined as:

```
// http://www.thecodingforums.com/threads/function-pointers-to-printf.317925/
/** @brief Printf-like signature of error handle functions to be used by SpSparse. */
typedef void (*error_ptr) (char const *str, ...);
extern pism::error_ptr pism_error;
```

The default implementation of pism_error would just call:
```
throw RuntimeError::formatted(...)
```

BUT... it would now be possible to replace pism_error() with your own error handler.  In my case, when calling from IceBin, I WOULD want to replace it.  (Exceptions turn out to be a problematic way to report errors in C++; if nothing else, because they provide no stacktrace.)

Are there any objections to this change?  I would not affect the behavior of PISM, but it WOULD change the way PISM code reports an error.

**Comment by citibeth** [comment]
I'm not sure this would always work, since sometimes PISM catches its own exceptions.

**Comment by ckhroulev** [comment]
I agree -- this would not work, and PISM's catching its own exceptions is just *one* of the reasons. (Overall, we can't easily "disable" exceptions in C++: that would require using an implementation of the standard library that does not throw, a non-throwing `new`, etc).

As for getting stack traces in PISM when an exception is thrown: see [Performing an action every time a PISM exception is thrown](https://github.com/pism/pism/blob/dev/doc/browser/coding_style.md#performing-an-action-every-time-a-pism-exception-is-thrown) in PISM's docs for an way to do it -- and let me know if it works for you.

**Comment by ckhroulev** [comment]
I am also very reluctant to have `pism_error` which is supposed **but is not guaranteed to** throw: this would mean that somebody would be able to break PISM's error handling by providing `pism_error` that returns without throwing an exception or throws an exception of a different (C++) type.
