### ISSUE TITLE
unclear how to (and unable to) make manual and browser [dev branch]

### ISSUE THREAD

**Issue by bueler** [pism/pism#342]
@ckhroulev @aaschwanden  I see in the current `INSTALL.md` that the documentation make targets have new names:
```
### Generating documentation

To generate PDF documentation:

    cd 'your build directory'
    make pism_manual              # builds pism_manual.pdf
    make pism_installation        # builds pism_installation.pdf
    make pism_forcing             # builds pism_forcing.pdf
```

I have built and tested PISM itself successfully, but the `pism_manual` target (and other doc targets I tested: `browser`, `pism_installation`) are unavailable:
```
$ make pism_manual
make: *** No rule to make target 'pism_manual'.  Stop.
```
I tried `manual` and `userman` targets too.

When I look at the `ccmake` options, I don't see `Pism_BUILD_DOCS` or similar, even under advanced options.  I also looked in `doc/` for make targets; no luck.

**Comment by ckhroulev** [comment]
This was an unintended consequence of 7b53ff5d78a00188dc4fe2c4608b79393e54a06e I failed to catch when merging that code into `dev`.

@citibeth: I don't think we want to make all of `doc/CMakeLists.txt` optional if `Pism_BUILD_PDFS` is not set. (Comments are welcome, though.)

**Comment by bueler** [comment]
Cool.  `make pism_manual pism_installation pism_forcing browser` now works for me.  Note `make browser` is activated by setting `Pism_BUILD_PDFS` to `ON`; perhaps the name `Pism_BUILD_DOCS` is more accurate?

**Comment by ckhroulev** [comment]
As far as I can tell the value of `Pism_BUILD_PDFS` should not affect the `browser` target in any way.

**Comment by ckhroulev** [comment]
[`CMakeLists.txt#L216`](https://github.com/pism/pism/blob/dev/CMakeLists.txt#L216) is the only place `Pism_BUILD_PDFS` is used.

**Comment by bueler** [comment]
Now I can use `make browser`.  Before 09a5052 I could not; I got a `No rule to make ...` error.

**Comment by bueler** [comment]
Thanks!
