### ISSUE TITLE
Consistent use of units in couplers

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#344]
Currently, the PSGivenClimate and POGivenClimate expect `kg m-2 s-1` while PAGivenClimate prefers `m s-1`. We should be consistent. I don't have strong preference but `kg m-2 s-1` seems the obvious choice.

**Comment by citibeth** [comment]
Kg m -2

**Comment by ckhroulev** [comment]
See the branch [`ckhroulev/precipitation-units`](https://github.com/pism/pism/tree/ckhroulev/precipitation-units).

**Comment by ckhroulev** [comment]
Fixed in `dev`.
