### ISSUE TITLE
Save PISM's compile-time configuration info in output files and print it when -version is set

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#345]
Currently one has to keep the build directory to be able to tell what choices were made when compiling PISM. (With/without debugging, which optional libraries were used, etc.)

**Comment by citibeth** [comment]
When PISM is built with Spack, this information is already stored in the
PISM install directory.

**Comment by ckhroulev** [comment]
This should include version numbers for **all the tools and libraries** used to build PISM (including CMake).

**Comment by citibeth** [comment]
Yes, Spack does that already.  Using Spack will make your life easier, implementing this stuff yourself will make your life harder (and the results not as good as what Spack will give you).

http://github.com/llnl/spack

**Comment by citibeth** [comment]
Here is the Spack recipe for PISM:

https://github.com/citibeth/spack/blob/efischer/develop/var/spack/repos/builtin/packages/pism/package.py

Building PISM with Spack is really not much harder than setting things up, then typing "spack install pism".

**Comment by citibeth** [comment]
Constantine,

Here's an example of the a PISM configuration coming out of Spack.  This
can be used to reliably re-build the exact same version in the future.

-- Elizabeth

Concretized
------------------------------
  pism@0.7.3%gcc@4.9.3+cxx11~doc~extra~icebin~parallel-hdf5~parallel-netcdf3~parallel-netcdf4+proj~python+shared
arch=linux-centos7-x86_64
      ^cmake@3.6.1%gcc@4.9.3~doc+ncurses+openssl~qt
arch=linux-centos7-x86_64
          ^ncurses@6.0%gcc@4.9.3 arch=linux-centos7-x86_64
          ^openssl@system%gcc@4.9.3 arch=linux-centos7-x86_64
      ^fftw@3.3.5%gcc@4.9.3+float+long_double~mpi~openmp~quad
arch=linux-centos7-x86_64
      ^gsl@2.1%gcc@4.9.3 arch=linux-centos7-x86_64
      ^netcdf@4.4.1%gcc@4.9.3~hdf4+mpi arch=linux-centos7-x86_64
          ^curl@7.50.1%gcc@4.9.3 arch=linux-centos7-x86_64
              ^zlib@1.2.8%gcc@4.9.3 arch=linux-centos7-x86_64
          ^hdf5@1.10.0-patch1%gcc@4.9.3+cxx~debug+fortran+mpi+shared~szip~threadsafe
arch=linux-centos7-x86_64
              ^openmpi@1.10.1%gcc@4.9.3~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt
arch=linux-centos7-x86_64
                  ^hwloc@1.11.3%gcc@4.9.3 arch=linux-centos7-x86_64
                      ^libpciaccess@0.13.4%gcc@4.9.3
arch=linux-centos7-x86_64
                          ^libtool@2.4.6%gcc@4.9.3 arch=linux-centos7-x86_64
                              ^m4@1.4.17%gcc@4.9.3+sigsegv
arch=linux-centos7-x86_64
                                  ^libsigsegv@2.10%gcc@4.9.3
arch=linux-centos7-x86_64
      ^petsc@3.7.2%gcc@4.9.3+boost~complex~debug+double+hdf5+hypre+metis+mpi+mumps+shared+superlu-dist
arch=linux-centos7-x86_64
          ^boost@1.61.0%gcc@4.9.3+atomic+chrono+date_time~debug+filesystem~graph~icu_support+iostreams+locale+log+math~mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals+singlethreaded+system+test+thread+timer+wave
arch=linux-centos7-x86_64
              ^bzip2@1.0.6%gcc@4.9.3 arch=linux-centos7-x86_64
          ^hypre@2.10.1%gcc@4.9.3~internal-superlu+shared
arch=linux-centos7-x86_64
              ^openblas@0.2.18%gcc@4.9.3+fpic~openmp+shared
arch=linux-centos7-x86_64
          ^metis@5.1.0%gcc@4.9.3~debug~gdb~idx64~real64+shared
arch=linux-centos7-x86_64
          ^mumps@5.0.1%gcc@4.9.3+complex+double+float~idx64~metis+mpi~parmetis~ptscotch~scotch+shared
arch=linux-centos7-x86_64
              ^netlib-scalapack@2.0.2%gcc@4.9.3~fpic+shared
arch=linux-centos7-x86_64
          ^parmetis@4.0.3%gcc@4.9.3~debug~gdb+shared
arch=linux-centos7-x86_64
          ^python@2.7.8%gcc@4.9.3~tk~ucs4 arch=linux-centos7-x86_64
          ^superlu-dist@5.0.0%gcc@4.9.3 arch=linux-centos7-x86_64
      ^proj@4.9.2%gcc@4.9.3 arch=linux-centos7-x86_64
      ^udunits2@2.2.20%gcc@4.9.3 arch=linux-centos7-x86_64
          ^expat@2.1.0%gcc@4.9.3 arch=linux-centos7-x86_64
