### ISSUE TITLE
More information on runtime errors.

### ISSUE THREAD

**Issue by matthiasmengel** [pism/pism#353]
I have a runtime error and PISM tells me 
```
* Initializing the Potsdam Cavity Model for the ocean ...
PISM ERROR: IceModelVec2T::update(int start): start = 0 is invalid
```
and that is it. Though PISM and Petsc are compiled with Debug options, I do not get any informations on
in which file and which lines this error occurs.
Couldn't we add such information, probably in `base/util/error_handling.cc`?
Seems like Petsc can provide [such information](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Sys/PetscError.html).

**Comment by ckhroulev** [comment]
I agree that providing the error location in the message printed by PISM may be useful, so I added some code to enable this. See the commit above.

PS: I recommend using a debugger to get this information. (In a debugger, set a breakpoint to `pism::RuntimeError::RuntimeError`, then run PISM. It will stop when the code throws a `RuntimeError` exception, i.e. right at the point of failure. You can then ask the debugger for the current location in the code, the backtrace, etc.)

PPS: PISM does not use the `PetscError` function from PETSc.

**Comment by matthiasmengel** [comment]
Thanks! This helps.
