### ISSUE TITLE
regridding of integer variables (masks)

### ISSUE THREAD

**Issue by matthiasmengel** [pism/pism#355]
For the ocean cavity model we need to regrid our mask for ocean basins (20 integer values) during bootstrap.
We currently use the standard regridding and have an additional routine that sets interpolated non-integer values back to integers.
Can this be done easier, i.e. is there a way to tell the `IceModelVec2 regrid` function to stick to integers?
This would also be useful for other masks read as input.

**Comment by ckhroulev** [comment]
> Can this be done easier?

Yes. Use `IceModelVec2Int` for masks, use the existing interpolation code, but replace `mask(i, j)` with `mask.as_int(i, j)` in the code that uses the mask.

> i.e. is there a way to tell the `IceModelVec2 regrid` function to stick to integers?

There is currently no way to do this.
