### ISSUE TITLE
Ananaconda environments prevent CMake from generating a safe runtime search path 

### ISSUE THREAD

**Issue by jhkennedy** [pism/pism#356]
On Debian based systems, the [PISM perquisites](https://github.com/pism/pism/blob/stable0.7/doc/installation/installation.tex#L170-L205) are typically installed via the system package manager. However, users using Anaconda to manage Python/R will encounter some issues, mostly revolving around the users `PATH` environment variable. 

A typical conda user will add conda to their `PATH` environment variable in their `.bashrc` file (or similar). For example, with anaconda 3 the export would look like:

```bash
export PATH=$HOME/anaconda3/bin:$PATH
```

Unfortunately, when the user goes to setup the [CMake build](https://github.com/pism/pism/blob/stable0.7/doc/installation/installation.tex#L362):

```bash 
PISM_INSTALL_PREFIX=~/pism cmake ..
``` 
They will see a series of CMake warnings that look like:

```bash
CMake Warning at src/CMakeLists.txt:255 (add_executable):
  Cannot generate a safe runtime search path for target bedrough_test because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [LIBRARY] in /usr/lib/[PATH] may be hidden by files in:
      /home/[USER]/anaconda3/lib

  Some of these libraries may not be found correctly.
```

`hdf5`, `gcc`, and `gfortran` are some of the conflicts. Proceeding with `make` at this point will cause PISM to try and link to a variety of libraries installed by anaconda, over the ones installed by the system manager, because they are found first on the users path. PISM *will* fail to build (as it should!). *Note, this is true if just anaconda has been added to `PATH`* **or** *if any conda environment is active.*

#### Solution ####
 
When you run `cmake`, pass it the `PATH` variable with conda removed:

```bash
PISM_INSTALL_PREFIX=~/pism PATH=$NOCONDA_PATH cmake ..
```

you can set the `NOCONDA_PATH` variable in your `.bashrc` (or similar) just before you add conda to your path like so:

```bash
export NOCONDA_PATH=$PATH
export PATH=$HOME/anaconda3/bin:$PATH
```

Once done, PISM will compile and pass all tests even when using an active anaconda environment like:

```bash
conda create --name PISM python=2 numpy scipy netCDF4 proj4 matplotlib basemap
```

which will encapsulate most of the python packages used by PISM. 

-----------

Note: when you activate a conda environment, it saves your current `PATH` into the `CONDA_PATH_BACKUP` environment variable, and when you deactivate that environment, it restores `PATH` to `CONDA_PATH_BACKUP` (and removes the backup variable). Therefore, if you activate a default conda environment in your `.bashrc`, it should be the *very last thing you do*, otherwise any paths exported after you activate the environment won't be in `CONDA_PATH_BACKUP`, and will then only exist in that environment. Any environment variables you want added to a specific conda environment should be done by the [conda env activate script](http://conda.pydata.org/docs/using/envs.html#saved-environment-variables).

**Comment by jhkennedy** [comment]
I've submitted this issue here, with the resolution, because this is a problem I've only encountered with PISM, even though it is a more general problem with the way Anaconda handles environments. 

I did not see this issue when compiling PETSc (I doubled checked the `CMakeCache.txt`) or other scientific software, so it might be related to how `CMakeLists.txt`is setup for PISM (?). 

Either way, it is easily resolved, so this issue serves to archive the problem for anyone else who may use Anaconda/Miniconda.

**Comment by ckhroulev** [comment]
@jhkennedy Thanks!

**Comment by citibeth** [comment]
A simpler approach is to use Spack to install everything.

**Comment by aaschwanden** [comment]
Thanks Joe.

I may have to consult you offline --- Anaconda on our new HPC cluster drives me nuts (but I have no issues with PISM like you describe it)

**Comment by matthiasmengel** [comment]
Thanks for this!
I had exactly the same problem and solved it the same way.
(ubuntu 16.04 + anaconda)

**Comment by jhkennedy** [comment]
@aaschwanden happy to consult --- I've been dealing with Anaconda here on Titan quite a bit. 

These are likely problems that would only be encountered on personal systems using the standard Anaconda and PISM install instructions; HPC systems tend to do things a bit differently.

**Comment by bueler** [comment]
Until now this is the most popular PISM issue ever.  So I changed the title from "Ananaconda" to "Anaconda".  Sorry, Joe.  Your 15 minutes--3 years--of fame may be over.  :smile:

**Comment by jhkennedy** [comment]
@bueler , Wow, that's quite the typo I made! Thanks for the fix. I'll actually update this for conda 4.4+ since the mechanics have changed a bit, but the problem is likely to persist. Maybe then I can keep my fame! ha!

**Comment by mgm-14392** [comment]
thank you! I had the same problem with openbabel, adding PATH=$NOCONDA_PATH to .bashrc and before cmake solved the issue

**Comment by Abbsalehi** [comment]
I did all the solutions, but nothing worked, so I renamed the Anaconda folder, and it worked for me.

`mv anaconda3 anaconda3_temp`

then run 

`cmake ..`

Once successfully built, then you can rename the anaconda folder.
