### ISSUE TITLE
Status of PISM + Python3?

### ISSUE THREAD

**Issue by citibeth** [pism/pism#359]
1. Does PISM's build require Python v2 or 3 or both?
2. Do PISM's Python bindings work for Python v2 or 3 or both?

This should be documented more clearly...

**Comment by ckhroulev** [comment]
1.  PISM does not use Python in the build process. (PETSc's build process requires Python 2.)
2.  PISM's Python bindings are tested using Python 2.7. Python 3.x is not supported.

**Comment by ckhroulev** [comment]
Regarding PETSc's `configure`:

```
~/local/petsc/petsc-3.7.3 $ PETSC_ARCH=py3 python3.5 ./configure --with-shared-libraries
Configure does not support Python 3 yet, please run as
  python2 './configure' '--with-shared-libraries'
```

**Comment by citibeth** [comment]
Good to know; can this be put in the docs?

**Comment by aaschwanden** [comment]
PISM's python bindings have now been updated and are compatible with python3. Hopefully, PETSc will soon support python3

**Comment by ckhroulev** [comment]
PISM's Python bindings in the new version (`v1.1`) support both Python 2.7 and Python 3.3+.

PETSc's `configure.py` still requires Python 2.7, although the next version of PETSc will support Python 3.x as well.
