### ISSUE TITLE
Ice with T < 10^6 K????

### ISSUE THREAD

**Issue by citibeth** [pism/pism#360]
I noticed the comment below... isn't that a little warm for ice?
```
/*! Treats ice at any temperature below 10^6 Kelvin as cold (= zero liquid fraction).

  The pressure dependence of the pressure-melting temperature is neglected.c;

  Note: Any instance of FlowLaw uses an EnthalpyConverter; this is
  the one used in cold mode verification code.
*/
class ColdEnthalpyConverter : public EnthalpyConverter {
```

**Comment by ckhroulev** [comment]
This is the special enthalpy converter that is used in **temperature-based verification tests only.** 

In these tests ice temperatures in an exact solution may exceed the pressure-melting temperature, but we still want to pretend that this ice is "cold" to ensure that the map from enthalpy to temperature is one-to-one. (Normally enthalpy is mapped to the `(temperature, water fraction)` pair; here water fraction is zero, so `enthalpy <--> (temperature, 0`.)

So, I had to pick a threshold (melting) temperature that is above all ice temperatures.

What is the issue?
