### ISSUE TITLE
TR1 being picked up even when user requested not to

### ISSUE THREAD

**Issue by citibeth** [pism/pism#361]
I'm calling `cmake` with the following arguments (among others):
```
    -DPism_CXX11=ON
    -DPism_USE_TR1=OFF
    -DPism_BUILD_EXTRA_EXECS=OFF
    -DBUILD_SHARED_LIBS=ON
    -DPism_BUILD_PYTHON_BINDINGS=OFF
    -DPism_BUILD_ICEBIN=ON
    -DPism_USE_PROJ4=ON
    -DPism_USE_PARALLEL_NETCDF4=OFF
    -DPism_USE_PNETCDF=OFF
    -DPism_USE_PARALLEL_HDF5=OFF
    -DPism_BUILD_PDFS=OFF
```
In spite of this, the CMake build decides to use `tr1` anyway.  It does so because when it tries to compile a test program using the C++11 standard, it fails.  Two problems here:

1. If the user requests `-DPism_USE_TR1=OFF` (or doesn't set it, since the default is OFF), then PISM should honor that --- EVEN IF it results in a build failure.  I've just spent a lot of time debugging this, laregely because PISM is trying to be too clever.

2. PISM's test for tr1 is broken see (you'll have to click through to the original Mantis issue):
https://gitlab.kitware.com/cmake/cmake/issues/15550

**Comment by ckhroulev** [comment]
Fixed in the `dev` branch by requiring that the compiler supports C++11. See 42eb02fae37f65c9e58ff80833c330c3bffd7cd6.

**Comment by citibeth** [comment]
Horray, long live C++11!
