### ISSUE TITLE
missing lat/lon values in pism output after bootstrapping (pism stable0.7)

### ISSUE THREAD

**Issue by tkleiner** [pism/pism#365]
In `IceModel::model_state_setup()` the method  `compute_cell_areas()` is called before the proj4 string from the input file was evaluated (see `std::string proj4_string = nc.get_att_text("PISM_GLOBAL", "proj4");` in `IceModel::misc_setup()`.  Therefore the method 
`IceModel::compute_cell_areas()`returns early without computing latitude and longitude values. 

How to check:
```
pism/examples/marine/circular$ ./circular_ice_sheet.py
pism/examples/marine/circular$ ncatted -O -h -a proj4,global,o,c,'+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs ' circular_withshelf.nc
pism/examples/marine/circular$ pismr -Mx 9 -My 9 -Mz 9 -Mbz 3 -Lz 4500 -Lbz 1000 -bootstrap -i circular_withshelf.nc -surface elevation -ocean pik -y 0 -o out.nc
pism/examples/marine/circular$ ncview out.nc
```
The patch below worked for me
[fix_empty_proj4.patch.txt](https://github.com/pism/pism/files/754817/fix_empty_proj4.patch.txt)

I think, lat/lon values should be initialized earlier. Some coupling methods (atmosphere,surface,ocean) could depend on lat/lon. 

Regards,
Thomas

**Comment by ckhroulev** [comment]
@tkleiner Thanks for reporting this (and the patch)!

(This issue is fixed in the `dev` branch already.)
