### ISSUE TITLE
Misleading parameter name for mantle density

### ISSUE THREAD

**Issue by jsegu** [pism/pism#366]
pism_config:lithosphere_density = 3300. ;
    pism_config:lithosphere_density_doc = "lithosphere density used by the bed deformation model. See [@ref LingleClark, @ref BLKfastearth]" ;

Looking at the original papers. Shouldn't this be called (or documented as) mantle density?

**Comment by ckhroulev** [comment]
@bueler: What do you think?

**Comment by bueler** [comment]
This is what you get when some damn mathematician chooses names which connect mere numbers to physical reality.

Julien is, not surprisingly, exactly right when I look at how that constant is used in the 2007 paper and how it is used in the code.  How about:
```
    pism_config:bed_deformation.mantle_density = 3300.0;
    pism_config:bed_deformation.mantle_density_doc = "half-space (mantle) density used by the bed deformation model. See [@ref LingleClark, @ref BLKfastearth]";
    pism_config:bed_deformation.mantle_density_type = "scalar";
    pism_config:bed_deformation.mantle_density_units = "kg meter-3";
```

**Comment by ckhroulev** [comment]
You're off the hook, Ed. Looks like [I am the one to blame](https://github.com/pism/pism/commit/150028b0166876a9639f68a4c55d275fe5fc5505#diff-c28fb26410252192148bd14b0b6af4b5) here.

**Comment by jsegu** [comment]
Just a matter of definition:
> -- Let lithosphere_density=3300.0 be the mantle density.

Thank you for the fix!
