### ISSUE TITLE
Temperature anomalies at processor boundaries

### ISSUE THREAD

**Issue by juseg** [pism/pism#371]
Probably not a bug in PISM, but I thought I would summarize here an ongoing email conversation with Constantine for the record.

In several runs I observe enthalpy/temperature anomalies around the processor boundaries (i.e. the processor grid is visible in PISM output). After investigation, it appears that the problem is specific to using the Cray-shipped PETSc library on the Cray XC40 supercomputer "Piz Daint". It is not clear yet if other computers are affected. Using an own PETSc build fixed the problem for me (see below).

The enthalpy anomalies are mostly positive, and propagate to other variables (temp, thk, etc). They are most important in the middle of the ice column, at and to a lesser extent downstream the processor boundaries. This makes me think that the problem is related to temperature advection.

You can quickly check if you are concerned by running the following code snippet, which will produce obvious artefacts in tempicethk_basal for buggy set-ups. This is Slurm syntax that works for me, but you might have to adapt it to your system.

    #!/bin/bash
    #
    #SBATCH --nodes=1
    #SBATCH --ntasks-per-node=36
    #SBATCH --time=24:00:00

    # environment variables
    export MPIDO="srun --ntasks-per-node 36"
    export PISMS="/users/jsegu/software/opt/pism-0.7.3/daint-gnu/bin/pisms"
    export PISMR="/users/jsegu/software/opt/pism-0.7.3/daint-gnu/bin/pismr"

    # prefix for output files
    run=run

    # prepare input file
    $MPIDO $PISMS -Tmin 263.15 -stress_balance ssa+sia \
        -Mx 121 -My 121 -Mz 31 -Lz 3000 -z_spacing equal -o input.nc -y 0

    # run PISM
    $MPIDO $PISMR -stress_balance ssa+sia \
        -i input.nc -o $run.nc -y 10000 \
        -extra_file ${run}-extra.nc -extra_times 1000 -extra_vars \
        enthalpy,temppabase,tempicethk_basal,thk,usurf,velbase_mag,rank

Problematic set-up:

* Computer: Cray XC40 Piz Daint (http://www.cscs.ch/computers/piz_daint).
* Processors: Intel Xeon E5-2695 v4 @ 2.10GHz (2 x 18 cores, 64/128 GB RAM).
* PETSc version: 3.7.2.1 (/opt/cray/pe/petsc/3.7.2.1/real/GNU/5.1/x86_64).
* PISM was configured by relying on Cray's module system to find PETSc:

      module add cray-petsc
      ccmake ..

Set-up that gives right-looking results on the same system:

* PETSc version: 3.7.5 (own build).
* PISM was configured by prepoluating the CMake cache with:

      set (PETSC_DIR    "$ENV{HOME}/software/opt/petsc-3.7.5/daint-gnu")
      set (PETSC_INCLUDES     "${PETSC_DIR}/include" CACHE PATH "")
      set (PETSC_LIBRARIES    "${PETSC_DIR}/lib/libpetsc.a" CACHE PATH "")

**Comment by ckhroulev** [comment]
This reminds me of #322, or, more specifically, [this bug in PETSc 3.6.0](https://bitbucket.org/petsc/petsc/issues/100/vecscatter-optimizations-in-petsc-36-break).

While this may not be a bug in PISM I agree that it is good to have it documented here because it affects PISM.

**Comment by talbrecht** [comment]
Thanks Julien, I checked with slurm for 16 tasks per node on the PIK cluster (Lenovo NeXtScale nx360M5, Xeon E5-2667v3 8C 3.2GHz, Infiniband FDR14; Lenovo/IBM). Both, PISM stable 0.7.3 with PETSc-3.3.7 and PISM dev with PETSc-3.7.5, all compiled with intel mpi, did not show artefacts...

**Comment by jsegu** [comment]
I tried with PETSc 3.7.2 own build on the same machine, no artefacts.
The problem seem specific to the Cray build.

**Comment by ckhroulev** [comment]
@jsegu If you're interested -- and have the time -- you could build and run [`vecscatter-bug.c`](https://bitbucket.org/petsc/petsc/issues/100/vecscatter-optimizations-in-petsc-36-break) from my old PETSc bug report (on the same machine, of course). There is a chance that it will confirm that Cray's PETSc build is flawed, which would (hopefully) make it easier to report it to Cray and get it fixed.

**Comment by jsegu** [comment]
I built the executable using the problematic Cray's PETSc, and ran it on 1, 2 and 4 processors. In all cases I end up with a matrix full of ones, no zeros.

I forgot to mention earlier, I use Cray's real (not complex) version of PETSc.

**Comment by ckhroulev** [comment]
> I forgot to mention earlier, I use Cray's real (not complex) version of PETSc.

Right. (PISM does not work with a complex build of PETSc. I am pretty sure it would not even compile.)

**Comment by ckhroulev** [comment]
Closing because it does not require any action at the moment.
