### ISSUE TITLE
default shear friction angle value

### ISSUE THREAD

**Issue by evangowan** [pism/pism#372]
The default value for tillphi (the shear friction angle of till) should be set to 30 degrees, as per the PISM manual. If bootstrapping is enabled, the value is set to 15 degrees instead. 15 degrees seems really low compared to actual measurements on till from the literature (i.e. Cuffey and Paterson 2010, page 268). Is there a reason why these values are different?

**Comment by ckhroulev** [comment]
This issue was fixed over a year ago (and merged into `master`), so it's time to close it.

> Is there a reason why these values are different?

No, I can't think of a good reason.
