### ISSUE TITLE
Struggling with height above flotation formula 

### ISSUE THREAD

**Issue by tkleiner** [pism/pism#379]
I wonder if the equation used in  `IceModelVec::Ptr IceModel_height_above_flotation::compute_impl()` that can be found in `src/base/iceModel_diagnostics.cc` (pism-dev 386eeea95) is correct. I think the equation should be
```
(*result)(i,j) = thk + std::min((ocean_density/ice_density * bed), 0.0);
```
similar to the equation used in `IceModel::ice_volume_not_displacing_seawater(...)` from `src/base/iMreport.cc`.

**Comment by ckhroulev** [comment]
Thomas,

Thanks for reporting this! This issue should be fixed now; please see [this commit](https://github.com/pism/pism/commit/5a65d3ce8a6dfaecfb1918225e31a6d811f25d04?diff=split).

The intended meaning is "the ice thickness is excess of the maximum floating ice thickness". I believe the formula should look like this (in pseudocode):

```
  ocean_depth = sea_level - bed_elevation;

  if (icy and ocean_depth > 0) {
    max_floating_thickness = ocean_depth * (ocean_density / ice_density);
    result = thickness - max_floating_thickness;
  } else {
    result = fill_value;
  }
```
