### ISSUE TITLE
Non-integer climate forcing period.

### ISSUE THREAD

**Issue by juseg** [pism/pism#380]
Is there a specific reason why climate forcing periods are restricted to [unsigned int](https://github.com/pism/pism/blob/dev/src/base/util/iceModelVec2T.hh#L141)? Period entered as floating-point numbers on the command-line are quietly rounded (and ignored if rounded to 0). I am interested in forcing PISM with daily-periodic input. What would it take to allow floating-point periods?

**Comment by ckhroulev** [comment]
The current code (`dev` branch) supports arbitrary period lengths.
