### ISSUE TITLE
Calculation of slvol in timeseries needs correction

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#388]
Looking into iMreport in function IceModel::ice_volume_not_displacing_seawater() we find 

`cell_ice_volume = thickness * m_geometry.cell_area(i,j);`

and for the marine parts

`max_floating_volume = (sea_level - bed)  * (sea_water_density / ice_density);`

which is not a volume yet if not multiplied by ` m_geometry.cell_area(i,j)`.  See 8c39ef9f9

This fix results in a observed sea-level equivalent grounded Antarctic volume of 56.7 m instead of 64.5 m (for a 15km regridded Bedmap2 setup)...

This is much closer to the estimates I found online, e.g. [~58m](http://www.antarcticglaciers.org/glaciers-and-climate/estimating-glacier-contribution-to-sea-level-rise/)?

**Comment by ckhroulev** [comment]
Thanks for the fix!
