### ISSUE TITLE
python bindings enthalpy converter test fails

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#389]
In dev, test 2 fails:

      Start  2: Python:nose:enthalpy:converter
 2/45 Test  #2: Python:nose:enthalpy:converter .....................................***Failed    0.84 sec

All other tests pass.

**Comment by ckhroulev** [comment]
This is normal: this test tries to run some code that is only compiled when PISM is configured in "debugging" mode and checks if a sanity check works the way it should. In the "release" configuration this sanity check (catching invalid inputs in the code converting (enthalpy, pressure) to temperature) is disabled, so the test complains:

```
$ ctest -R Python:nose:enthalpy:converter -V
...
2: AssertionError: failed to catch E > E_liquid in temperature()
...
```
