### ISSUE TITLE
cmake deprection warning

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#393]
With cmake 3.9.1, I'm suddenly seeing

 CMake Deprecation Warning at CMakeLists.txt:19 (cmake_policy):
   The OLD behavior for policy CMP0026 will be removed from a future version
   of CMake.

For now it's just a warning.

**Comment by ckhroulev** [comment]
Yup. I see it every time I build PISM, so I'm not going to forget to deal with this. :-)

**Comment by ckhroulev** [comment]
Fixed in `dev` (and will be fixed in the upcoming release).
