### ISSUE TITLE
How to account for changing marine ice and ocean load in the bed deformation model

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#395]
I openend this issue for a discussion on how to treat changing ice loads in the marine ice case (with focus on ice shelves in Antarctica). So far (and please correct me, if I am wrong) the PISM bed deformation model considers changes in ice thickness (rhoi*thk) to force a corresponding bed displacement. This includes the ice shelves, where a change in ice thickness in fact should not change the load (see  #363). 

But there are also changes in the load as a result from varying depth of the surrounding ocean (including the ice shelf region), in particular on paleo time scales with sea-level variation by about 100m. This might be a second order effect, but there is also a feedback of the bed displacement itself, which changes the water column and hence the load. Speaking of several hundred's meters of bed elevation change between glacial and interglacial state this feedback can get important.

I see, that the second part (including change in ocean load) might be complicated to add into the current implementation (the average far-field displacement should always be 0, right?) But maybe we can have a water depth (load) change at least within the typical horizontal length scale (1000km?) around the ice sheet? Hence the bed deformation model would need to know also about the bed elevation and the current sea-level...

**Comment by talbrecht** [comment]
I had some discussions with Pippa Whitehouse and she suggests that the missing effects of load changes in the PISM bed deformation model may not be of second order. I made some plots to visualize what is happening (see below) in the case of uniform sea-level change, bed deformation change and ice thickness change (here by 200m). The changes in water column thickness (dsl and dbed) are one aspect (dashed lines). For a moving grounding line we have a region between start and end where the load changes linearily (dotted line). Regarding LGM and present day state this region can encompass the large ice shelf basins.

The other aspect seems even more problematic (and has been addressed already in #363), because ice shelves act as load (as far as I can overlook the code) and hence the whole ice shelf region (dh) contributes to load changes. 

I am looking for a quick and simple change (optional) in the earth code in PISM to check for these effects and thought of passing the (ice-equivalent) load thickness (including the water column) instead of ice_thickness to the FFT solver:

ice_equivalent_load_thickness = max(thk - rhow/rhoi*(sl - bed), 0.0) + rhow/rhoi*(sl - bed)

In this way the whole computational domain including the ocean would act as load around the ice sheet and I hope Nx and Ny are chosen large enough to still allow for periodic boundaries?! @ckhroulev, it would be so nice if you could help me with this?

![load_change_pism](https://user-images.githubusercontent.com/1190987/31758787-25f1bc20-b4af-11e7-9427-4f271953cec7.png)

see plot code[ here](http://www.pik-potsdam.de/~albrecht/pism_repro/bed_deformation/).

**Comment by ckhroulev** [comment]
@talbrecht: I need to re-formulate PISM's bed deformation models in terms of of "load amount" (mass per unit area, which is exactly the density*thickness you mention). This way bed deformation models need not know about the nature of the load (and its density in particular).

I agree that in the short term providing the load in terms of the ice-equivalent thickness is the right idea, but I don't have the time to work on it right now -- got to get the next PISM release out the door. (I'll get back to this and #363 once I'm done with the release.)

Regarding the FFT grid size: I agree that you probably have to increase it. I added a new configuration parameter to make this easier: see `bed_deformation.lc.grid_size_factor`.

**Comment by talbrecht** [comment]
Thanks @ckhroulev , I can understand your priority, looking forward to the new stable version.
Regarding this issue I added the ocean load in a simple way,  see [here](https://github.com/talbrecht/pism_pik/commit/f383fb64f281e77b89804abe69f381598cbff6c0). It compiles, but I haven't tested it yet. I could not find a way yet to access the current sea-level of the ocean model. I would be happy for any hint.

**Comment by talbrecht** [comment]
I forgot to change ice_thickness to m_load also in the bootstrap() and init() functions of PBLingleClark.cc which is passed to the BedDeformLC object. -beddef iso and lc now give reasonable results for changing ice and ocean loads, see[ here](https://github.com/talbrecht/pism_pik/commit/87ad6dd59506356e2bd72403ffc2309dc916bc0e). However, accessing the ocean model to get the current sea-level seems problematic. Haven't tested reproducability and restartibility yet.

**Comment by ckhroulev** [comment]
@talbrecht The solution is to compute the load  (including the influence of sea level changes) in `IceModel`, convert it to ice-equivalent thickness, and pass that to the bed deformation model in `IceModel::step()` **instead of ice thickness** using `BedDef::update(thickness, t, dt)`. The LC bed deformation model would need only one modification: in `PBLingleClark::init_impl()` you need to get the ice load field instead of ice thickness.

**Comment by talbrecht** [comment]
Great, good idea, this works for me, see [here](https://github.com/talbrecht/pism_pik/commit/4104446e90f9401e5c4eb8d1ca6790cf011e078d). It took me a while to find a workaround in` iMinit.cc` to first init the beddef model and get the `bed_topography`, which is needed for the calculation of the load thickness, which then feeds into the beddef:init model again... I guess other users would like to use this update. Should this code be adjusted and merged into dev? After some more testing?

**Comment by ckhroulev** [comment]
I have thought about it more recently and concluded that PISM's bed deformation model cannot handle loads that extend to the edge of the domain the way the ocean load does in whole-ice-sheet simulations.

**Comment by bueler** [comment]
@ckhroulev  I think you are correct.

My guess: If someone really wants ocean load to affect the sea level seen by PISM, for 2-way coupling, then they need to run a global, spherical earth deformation model and handle the load-and-bed-geometry coupling themselves.

**Comment by talbrecht** [comment]
Yes, agree.. The PISM coupling with VILMA works just fine, and this additionally solves self-consistently for the sea level equation. PISM interprets all change in relative sea level is change in bed topography, as ice dynamics follow the geoid. 
But I remember that my tests with accounting for changes in ocean load (I used it in the ensemble) within the computational domain worked fine as the bed deformation domain is four times larger (enough space to converge) and the FFT seem to cope with the steep gradients during glacial period with 100m lower surface elevation. That's why I though it could be an option?! But I am fine with closing this issue...
