### ISSUE TITLE
compatibility of SIA dynamics since stable0.7.3

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#399]
Mark Pittard and me had some discussions lately on reproducing results of stable0.7.3 with the new stable1.0 version. We have compared results of the SeaRISE-Antarctica experiment, which for stable1.0 yields for default settings a collapse of WAIS. We also found very different computational costs/speeds (factor 2-3) of those simulations for both stable PISM versions dependent on the used HPC (choice of intel compiler helped a bit for stable1.0).

We then started to investigate dynamical reasons for the different computation times we found in the pisms (A) experiment (ran into equlibrium) quite some difference in the SIA-diffusivity, enthaply and tillwat pattern close to the ice front (for different resolutions and "pb" flow law). And since max_diffusivity limits the adaptive time step this could explain the difference in simulation speed. Question is, what is the reasons for this difference in (SIA?) dynamics and could this be a bug that needs to be solved?

See[ here](https://nbviewer.jupyter.org/url/www.pik-potsdam.de/~albrecht/notebooks/check_version_compatibility.ipynb) for plots and link to the used PISM command.

**Comment by talbrecht** [comment]
Mark suggested that enthalpy advection and strain-heating near the margins could be a reason, as discussed in #292 and changed in 260edd7 on March 28th, 2016, since SIA-diffusivity depends on ice softness and hence on temperature/enthalpy. This commit did not enter into stable0.7 but ii made it into stable1.0 version. Unfortunately I cannot compile the old code any more but I ran a simulation in which I re-added those changes, and yes, stable0.7 pisms (A) results were reproduced exactly... However, I wasn't aware that pisms A used the cold mode temperature based energy code.

**Comment by mlpittard** [comment]
As extra information, I find there to be quite a large difference (not just a little bit) in the simulation run times depending on whether you are running PISM stable 1.0 compiled with gcc (4.9.3) or Intel (17). I have included the PISM stable 0.7.3 gcc compiled version as well as reference.

The exact code I ran was (Which I think is the same as the first run in the above code):
'mpiexec -n 1 pisms -Mx 30 or 50 -My 30 or 50 -Lz 6000.0 -ys 0 -ye 20000 -ts_file 20000yrs.nc -ts_times 0:"100":20000 -ts_vars dt,ice_volume_glacierized,slvol,max_hor_vel,max_diffusivity -o test_50km_20000yrs.nc'

**Simulation Times and final max diffusivity for 50km:**
pism_stable_1.0_gcc =1.2 million model years per proc hour, 2.601
pism_stable_0.7.3_gcc =8.2 million model years per proc hour, 0.838
pism_stable_1.0_intel = 4.6 million model years per proc hour, 2.601

**Simulation Times and final max diffusivity for 30km:**
pism_stable_1.0_gcc =0.3 million model years per proc hour, 0.88640
pism_stable_0.7.3_gcc = 1.4 million model years per proc hour, 0.68
pism_stable_1.0_intel = 1.3 million model years per proc hour, 0.98059

So similar to Torsten above, I find a likely diffusivity related slowdown for my pism 1.0 runs relative to pism 0.7, but as you can also see, using gcc to compile pism stable 1.0 causes further issues. pism 0.7 doesn't seem to compile with intel compiled petsc, so I haven't followed up that configuration yet. 

In terms of the enthalpy change, I am finding it has made WAIS incredibly unstable, with very minor physical changes leading to the collapse of the ice sheet. It creates a dipole of diffusivity change near PIG and Thwaites, with both a region of high diffusivity and low diffusivity relative to 0.7.3. It also seems sensitive to small changes, as for example, I found running the same physics on 24 cpu's will have a stable WAIS, while, 128 cpu's will have a collapsed WAIS. This suggests to me it is very sensitive to ssa velocities (as my understanding is they might be sensitive to cpu choice). I will try to reproduce the above findings using the standard searise experiment.

Cheers,
Mark Pittard

**Version information below**

pism_stable_1.0_intel pismr -verison (all dependants installed with intel as well)
---------------------------------------

:source = "PISM (stable v1.0-27-g7cf3e4a committed by Constantine Khrulev on 2017-11-21 14:02:18 -0900)\n",
"CMake 3.6.2.\n",
"Petsc Release Version 3.8.3, unknown \n",
"PETSc configure: CFLAGS=\"-fp-model precise -march=native -no-fast-transcendentals\" CXXFLAGS=\"-fp-model precise -march=native -no-fast-transcendentals\" --with-cc=mpicc --with-cxx=mpiCC --with-fc=0 --with-shared-libraries --with-debugging=0 --download-f2cblaslapack=1 --with-64-bit-indices=1 --known-mpi-shared-libraries=1 --with-x=0 --with-ssl=0\n",
"OpenMPI 2.1.1\n",
"NetCDF 4.5.0 of Jan 22 2018 23:20:01 $.\n",
"FFTW fftw-3.3.7.\n",
"GSL 2.3.\n",
"PROJ.4 Rel. 4.9.3, 15 August 2016.\n",

pism_stable_1.0_gcc -version (all dependants installed with gcc as well)
--------------------------------
:source = "PISM (stable v1.0-27-g7cf3e4a committed by Constantine Khrulev on 2017-11-21 14:02:18 -0900)\n"
CMake 3.6.2.
Petsc Release Version 3.7.6, Apr, 24, 2017 
PETSc configure: --prefix=/ddn/apps/Cluster-Apps/petsc/ompi-2.1.1/gcc-4.9.1/3.7.6 --with-shared-libraries=1 --with-mpi=1 --download-fblaslapack=1 FC=mpif90 F77=mpif77 CC=mpicc CXX=mpiCC --with-debugging=0 COPTFLAGS=-O3 CXXOPTFLAGS=-O3 FOPTFLAGS=-O3 --with-valgrind=1 --with-valgrind-dir=/usr/local/Cluster-Apps/valgrind/3.9.0
			"OpenMPI 2.1.1\n",
			"NetCDF 4.5.0 of Jan 22 2018 23:20:01 $.\n",
			"FFTW fftw-3.3.7.\n",
			"GSL 2.3.\n",
			"PROJ.4 Rel. 4.9.3, 15 August 2016.\n",

pism_stable_0.7.3 would have been installed with the below
-----------------------------------------------------------------
PETSc configure: --prefix=/ddn/apps/Cluster-Apps/petsc/ompi-2.1.1/gcc-4.9.1/3.7.6 --with-shared-libraries=1 --with-mpi=1 --download-fblaslapack=1 FC=mpif90 F77=mpif77 CC=mpicc CXX=mpiCC --with-debugging=0 COPTFLAGS=-O3 CXXOPTFLAGS=-O3 FOPTFLAGS=-O3 --with-valgrind=1 --with-valgrind-dir=/usr/local/Cluster-Apps/valgrind/3.9.0
OpenMPI 2.1.1
NetCDF 4.4.1.1 of Jun 27 2017 12:31:05 $.
FFTW fftw-3.3.
GSL 1.15.

**Comment by ckhroulev** [comment]
The new release (`v1.1`) reverts back to the `v0.7`-style treatment of strain heating at ice margins (i.e. it is ignored). See `CHANGES.rst` for an explanation.

Please re-open if this is still relevant.
