### ISSUE TITLE
Reproducibility of -bed_def lc runs is affected by non-determinism in FFTW

### ISSUE THREAD

**Issue by tkleiner** [pism/pism#402]
I found that our spin-up simulations for Antarctica using PISM stable0.7 can lead to very different results (calving front position, ice area, ice volume, ...) running the model again and again with the same setup (copy batch files from one folder to another). These simulations can also show a very different transient behaviour (about 0.5 m difference in sea level equivalent ice volume). Some of the runs crash while other survive. In #377 it has been reported, that the choice of `-bed_def lc` breaks the reproducibility of runs in pism-dev at that time (now stable1.0), but stable0.7 is also affected.

It is possible to reproduce the reported behaviour by using a simple circular ice sheet with ice shelf on a coarse grid running serial for 1000 model years within a few minutes. Running the model in serial avoids issues from the parallel architecture of the machine. I use `nccmp.py -v timestamp -x ...` from PISM to check if the output files `*_out1.nc` are identical. Unfortunately, this is not an automated process until now. 

For PISM stable0.7 serial runs with `-bed_def lc` are not reproducible. The best agreement can be achieved without `-pik` option. Calving front related options add a little bit to the difference between individual runs, while using the sub-grid grounding line `-subgl` option causes the most trouble. The same holds for PISM stable1.0, but to a lesser extent.  

I have tried to reduce the complexity of the model to isolate the bug, but I have the feeling, that we have several issues playing together (`-bed_def lc`+ `-pik`+ parallel vs. serial). The best candidate to start debugging the code would be the coarse grid serial experiment with PISM stable1.0 with only `-subgl` from the list of PIK options and `-bed_def lc`.

Some of the experiments, I have already done, are given below the setup section. More runs would be helpful for a better statistic.

Please let me know how I can help.
Thomas

**Setup details:**

* tested PISM versions: 
  stable0.7 (stable v0.7.3-15-g42b05ca) with patch for #349 (`pism_config:mask_is_floating_thickness_standard = 0.0;`) and 
  stable1.0 (stable v1.0-27-g7cf3e4a)
* PISM and external packages are compiled via 
[build_pism_ollie.sh.txt](https://github.com/pism/pism/files/1731078/build_pism_ollie.sh.txt)
(remove '.txt') using Intel compiler + Intel MPI (v18.0.1) on Cray's CS400 Cluster "Ollie" at AWI. 
* simplified geometry setup `circular_withshelf.nc` from
`examples/marine/circular/circular_ice_sheet.py` (same file for stable0.7 and stable1.0) 
* high resolution grid mainly for parallel runs
```grid="-periodicity none -Mx 381 -My 381 -Lz 5500 -Lbz 2000 -Mz 81 -Mbz 21"```
and low resolution grid for serial runs 
```grid="-periodicity none -Mx 121 -My 121 -Lz 5500 -Mz 3"```
* bed deformation (`-bed_def iso,lc,none`)
* model runs in time slices of 1000 years with restarts (although restarting is not required to reproduce this issue)
* run each setup 5 times for reproducibility testing
* parallel (2 nodes = 72 cores) and serial runs 

The PISM options and the high resolution grid are chosen according to our InitMIP setup for Antarctica, but the geometry is just circular with very simple climate to avoid the need of pre-processing data. This setup is able to address the related issues #377 and #399. (runscript 
[circular_bed_def_restarted.sh.txt](https://github.com/pism/pism/files/1731241/circular_bed_def_restarted.sh.txt) and example slurm batch file 
[run_circular_bed_def_restarted.batch.txt](https://github.com/pism/pism/files/1731242/run_circular_bed_def_restarted.batch.txt) for Ollie)

**Selected test results (high resolution)**

parallel runs PISM stable0.7:
* figure `ivol-72cores_PISM0.7-circular_withshelf_beddef_all_ts1.png`
![ivol-72cores_pism0 7-circular_withshelf_beddef_all_ts1](https://user-images.githubusercontent.com/5449934/36305194-d4237808-1312-11e8-8e7a-4003f1652536.png)
* Runs with  `-bed_def iso` appear to be the same for the shown ice volume. The runs are indeed identical after 1000 model years according to `nccmp.py file1.nc file2.nc`.
* Runs with `-bed_def lc` diverge already after about 100 model years or crash. 
* All model runs with  `-bed_def none` crash after 200 model years.

parallel runs PISM stable0.7 (No `-pik`):
* All runs with  `-bed_def iso` are identical after 1000 years. The same holds for  `-bed_def none`.
* Runs with  `-bed_def lc` differ by less than 1e-6 m ice thickness.

parallel runs PISM stable1.0:
* figure `ice_volume_glacierized-72cores_PISM1.0-circular_withshelf_beddef_all_ts1.png`
![ice_volume_glacierized-72cores_pism1 0-circular_withshelf_beddef_all_ts1](https://user-images.githubusercontent.com/5449934/36305225-f7e37a54-1312-11e8-977d-c347ea594085.png)
* All runs with  `-bed_def iso` and `-bed_def none`, respectively, are identical after 1000 years (`nccmp.py ...`)
* Runs with  `-bed_def lc` appear to be the same for the ice volume, but differ e.g. in ice thickness by about 700 m.
* Runs with  `-bed_def iso` differ from the same runs with PISM stable0.7 (see also #399).

parallel runs PISM stable1.0 (No `-pik`):
* All runs with  `-bed_def iso` are identical after 1000 years. The same holds for  `-bed_def none` and  `-bed_def lc`.

serial runs PISM stable0.7:
* figure `ivol-serial_PISM0.7-circular_withshelf_beddef_all_ts1.png`
![ivol-serial_pism0 7-circular_withshelf_beddef_all_ts1](https://user-images.githubusercontent.com/5449934/36305241-0792452a-1313-11e8-8a9b-46c3d2a3d9c4.png)
* All runs reach the end of the 1000 year time slice. 
* All runs with  `-bed_def iso` are identical after 1000 years. The same holds for  `-bed_def none`.
* Runs with `-bed_def lc` appear the same (for ice volume), but differ in ice thickness by about 900 m (`nccmp.py -v thk file1.nc file2.nc`).
* The serial runs with `-bed_def iso` differ from the parallel runs. 

serial runs PISM stable1.0:
* figure `ice_volume_glacierized-serial_PISM1.0-circular_withshelf_beddef_all_ts1.png`
![ice_volume_glacierized-serial_pism1 0-circular_withshelf_beddef_all_ts1](https://user-images.githubusercontent.com/5449934/36305254-188745c4-1313-11e8-9692-950cf025fa6c.png)
* All runs with  `-bed_def iso` are identical after 1000 years. The same holds for  `-bed_def none`.
* Again, runs with `-bed_def lc` appear the same (for ice volume), but differ in ice thickness by about 600 to 700 m.

**Selected test results (low resolution, serial only)**

serial runs PISM stable0.7 (`-pik`):
* All runs with  `-bed_def iso` are identical after 1000 years. The same holds for  `-bed_def none`.
* Runs with `-bed_def lc` differ in ice thickness by about 400 to 500 m.

serial runs PISM stable0.7 ( No `-pik`):
* All runs with  `-bed_def iso` are identical after 1000 years. The same holds for  `-bed_def none`.
* Runs with `-bed_def lc` differ slightly in ice thickness (< 2.e-11 m).

serial runs PISM stable0.7 (`-subgl` from PIK only):
* All runs with  `-bed_def iso` are identical after 1000 years. The same holds for  `-bed_def none`.
*  Runs with `-bed_def lc` differ in ice thickness by about 500 to 600 m.

serial runs PISM stable0.7 (`-cfbc -kill_icebergs -part_grid` from PIK only):
* All runs with  `-bed_def iso` are identical after 1000 years. The same holds for  `-bed_def none`.
* Runs with `-bed_def lc` differ slightly in ice thickness (< 3.e-8 m).

serial runs PISM stable1.0 (`-pik`):
* All runs with  `-bed_def iso` are identical after 1000 years.  The same holds for  `-bed_def lc` and `-bed_def none`. **More runs required!**
* Most runs with `-bed_def lc` are identical also 2000 years. After 3000 years the runs differ by about 2m - 700 m in ice thicknes (Stil an issue with restarts?)

serial runs PISM stable1.0 (`-subgl` from PIK only):
* All runs with  `-bed_def iso` are identical after 1000 years. The same holds for  `-bed_def none`.
* One run out of five with `-bed_def lc` differs in ice thickness by about 570 m. **More runs required!**

serial runs PISM stable1.0 (`-cfbc -kill_icebergs -part_grid` from PIK only):
* All runs with  `-bed_def iso` are identical after 1000 years. The same holds for  `-bed_def none`.
* Runs with `-bed_def lc` are identical after 1000 years, but one run differs slightly in ice thickness (< 3.e-11 m) after 3000 years. **More runs required!**

serial runs PISM stable1.0 ( No `-pik`):
* All runs with  `-bed_def iso` are identical after 1000 years.  The same holds for  `-bed_def none`.
* One run out of five with `-bed_def lc` differs in ice thickness by about 1.5e-11 m. **More runs required!**

**Comment by mlpittard** [comment]
I am planning on using the Lingle-Clark deformation, so I have run some tests with a more complex topography. I have been running the full Searise example on PISM stable1.0 with the lingle clark bed deformation and over four runs (two with just -bed_def lc and two with -bed_def lc and -calving_cfl) and can confirm a similar story. For clarity, this is just antspin-coarse.sh from examples/searise/, and I have plotted the run_30km output for the four runs. The runs with just bed_def added deviated after around 10k years, while with calving_cfl added it deviated at 60k years. I'll need to run them a few more times to see if the divergence occurs at the same point, and i'll also try some more combinations of parameters. 

[ts_volume.pdf](https://github.com/pism/pism/files/1740017/ts_volume.pdf)

Cheers,
Mark

**Comment by talbrecht** [comment]
@tkleiner , I have tried to repeat some of your circular-shelf runs on the PIK HPC, for PISM stable1.0 (stable v1.0-27-g7cf3e4a), and ran 9 tests (without restarts) for 1000 years each and for the three beddef cases lc, iso and none:
* I can confirm, all runs are identical after 1000 years when using `-bed_def iso` or `-bed_def none` and I have not observed any crashes. See[ my notebook](https://nbviewer.jupyter.org/url/www.pik-potsdam.de/~albrecht/notebooks/check_reproducibility_circular.ipynb) for plots.

* If using  `-bed_def lc` I find divergence for option` -pik`:
    - for serial runs (and 30km resolution) I find 4 different solution in 9 runs, which diverge already after the first 5 model years. Also the serial run uses iterative solver, as far as I know. Ice volume at the end of the run differs by less than 0.2%. However, ice shelves grow against the computational boundary with lots of buttressing.
    - for parallel runs using 2x16 CPU (and 9.5km resolution), I find only one outlier out of 9 with 0.03% difference in ice volume at the end of the 1000 yr run. Differences in ice thickness of up to 700m can be found in single cells at the steep ice margin, and almost no ice shelves any more.
    - for parallel runs using 2x16 CPU (and 9.5km resolution) for the [pism_pik_1.0 code](https://github.com/talbrecht/pism_pik/tree/pism_pik_1.0) again only one outlier out of 9
    - for parallel runs using 2x16 CPU (and 9.5km resolution), but starting the runs from one and the same 100 year model result using option `-i `without` -bootstrap`, I find again one outlier in 9 runs.
    - for parallel runs using 2x16 CPU (and 9.5km resolution), but using a larger `pism_config:bed_deformation.lc.grid_size_factor = 8` (instead of 4) for the `viscous_bed_displacement` field, I get 7 divergent solutions out of 9 with up to 0.8% difference in ice volume.

* If using  `-bed_def lc` and option` -pik` without `-subgl`:
    - for parallel runs using 2x16 CPU (and 9.5km resolution), I find two outlier out of 9, but with only O(1e-13%) difference in ice volume
* If using  `-bed_def lc` and` -pik` but with `-no_subgl_basal_melt`:
    - for parallel runs using 2x16 CPU (and 9.5km resolution), I find again one outlier out of 9, with 0.09% difference in final ice volume
* If using  `-bed_def lc` and no ` -pik` :
   - for parallel runs using 2x16 CPU (and 9.5km resolution), I find no outlier so far in 5 runs. However, simulations are extremely slow (about 1/10 of simulations with `-pik`). Also, I think that eigencalving does not work without` -part_grid` and boundary conditions for the ice shelves are ill-posed without `-cfbc`, such that ice shelf front propagates against the computational boundary.

I find in this comparably short test simulation for parallel runs around 1/9 outliers with little divergence already after a few model years. Serial runs seem worse, and difference without` -subgl` much smaller. From experience I can tell, that for one reference simulation (35,000 model years deglaciation on similar grid), which I have ran for at least 20 times of the last year, I have not found any divergence through the whole simulation using [pism_pik_1.0 code](https://github.com/talbrecht/pism_pik/tree/pism_pik_1.0), mentioned above. But I agree, if there was divergence in these kind of simulations, they could sum up to quite some different final results, particularly in a non-linear dynamical regime.

Torsten

PS: In your example script there is a` -pik` option left within the options?!
PPS: Divergence can be easiest seen in maximum velocity time series.

**Comment by mlpittard** [comment]
As a quick follow up - I ran the first 1000 years of the Searise experiment with -bed_def lc 24 times on 8 CPU's. I found 4 unique solutions as well, which is curious given that Torsten found 4 unique solutions as well when running 30km resolution (same as searise).

**Comment by talbrecht** [comment]
Variation of the parameter `pism_config:bed_deformation.lc.grid_size_factor = 4` for the size of the `viscous_bed_displacement` field in both directions has quite some influence on the reproducibility. Could it be that the LC beddef model is the root of occasional divergence and other options like `-subgl` just amplify the divergent solutions?!

**Comment by ckhroulev** [comment]
@tkleiner, @mlpittard, @talbrecht: Thank you for reporting this and for performing all the test runs!

I committed a change that should fix this -- if we're lucky. (See the commit message for an explanation.)

Please re-run your tests and let me know if the issue goes away. Thanks!

**Comment by talbrecht** [comment]
Yes! No divergence found in 100 serial simulations for 10 model year each... I check now for the parallel case... Thanks Constantine!

**Comment by tkleiner** [comment]
I re-run the serial tests with pism (development v1.0-174-g2d5d9dd) using 
[circular_bed_def_restarted.sh.txt](https://github.com/pism/pism/files/1770506/circular_bed_def_restarted.sh.txt) and found that the results are identical (nccmp.py -v thk) for all 20 runs. The results are identical also after 3 restarts (`*_out4.nc`). I run this experiment also on two nodes (72 cores) with higher resolution. All 20 runs are identical after 1000 years. 

Thank you, Constantine! Reproducibility was a serious issue for quite a while.

**Comment by ckhroulev** [comment]
This is fixed in all recent PISM versions (`v0.7`, `v1.0`, `v1.1`, and the developmental branch).
