### ISSUE TITLE
Consider using string_printf()

### ISSUE THREAD

**Issue by citibeth** [pism/pism#406]
See here:
   https://github.com/citibeth/ibmisc/blob/master/slib/ibmisc/string.cpp

Could be useful for `pism_utilites.cc`, instead of being bounded by `TEMPORARY_STRING_LENGTH`.  Permission is granted to copy this subroutine and use within PISM without attribution or any other encumbrances.

**Comment by ckhroulev** [comment]
I decided to use a different version from http://codereview.stackexchange.com/questions/52522/mimic-sprintf-with-stdstring-output

Thanks for the suggestion, though!
