### ISSUE TITLE
Asymmetry in PICO model using a symmetric, idealized setup

### ISSUE THREAD

**Issue by JohannesFeldmann** [pism/pism#408]
Testing PICO (dev branch version) in a simplified, symmetric channel-type setup of an ice-sheet-shelf system reveals that there is an asymmetry in the computation of the PICO melt rates (and related fields, i.e., pico_box_mask, pico_shelf_mask, pico_overturning, pico_temperature, pico_salinity). In other words, the melt-rate computation does work for only one of the two symmetric ice shelves in the setup, the other one does not seem to be detected. Note that pico_contshelf_mask and pico_ice_rise_mask are symmetric, as they should be. One guess is that the detection of lakes does not work as it should and is the reason for the asymmetry in the shelf_mask, but this is very speculative. Another point is that in the present simplified setup the ice sheet is not fully surrounded by ocean in contrast to a setup of the entire Antarctic ice sheet for which PICO was originally designed. 

Find attached a minimal example of a model run showing the asymmetry (all available PICO-related diagnostic fields are written to the subfolder "extras").
[MinimalExamplePICO.zip](https://github.com/pism/pism/files/2035294/MinimalExamplePICO.zip)

**Comment by ckhroulev** [comment]
@JohannesFeldmann : Please let me know if you think that this issues needs more work.

**Comment by JohannesFeldmann** [comment]
Works well, thanks! Don't see any further work to be made on that.
