### ISSUE TITLE
Update to the new (version 5) PROJ.4 API

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#409]
See https://proj4.org/development/migration.html

**Comment by ckhroulev** [comment]
See https://github.com/OSGeo/proj.4/issues/836

In the meantime we need to add

``` c++
#define ACCEPT_USE_OF_DEPRECATED_PROJ_API_H
```

to `src/util/Proj.hh`.

**Comment by citibeth** [comment]
@ckhroulev @adamjstewart Do you know if any released versions of PISM  require or allow PROJ.6?  Or do all released versions still need to work with PROJ.4?

**Comment by ckhroulev** [comment]
@citibeth Thanks for the nudge! Please see https://github.com/pism/pism/releases/tag/v1.1.4

I will switch to PROJ v6 when I get a chance. (I updated the code but had to put it on the back burner for now since I have more pressing tasks to work on.)

**Comment by ckhroulev** [comment]
Done in the `dev` branch and will be a part of the next release.
