### ISSUE TITLE
Bed deformation model 'iso' causes Segmentation Violation

### ISSUE THREAD

**Issue by sebhinck** [pism/pism#418]
Using the Pointwise Isostasic bed deformation model results in an error:

> PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range

This is solved by adding m_topg_last to the AccessList in `src/earth/PointwiseIsostasy.cc` line 81.

**Comment by ckhroulev** [comment]
Thanks for reporting this! I added a regression test to make sure to make sure this bug does not re-appear in the future.
