### ISSUE TITLE
LingleClark model should be updated using dt_beddef

### ISSUE THREAD

**Issue by sebhinck** [pism/pism#423]
I have discovered a bug in the LingleClark earth deformation model on the dev branch.
When I was running a transient setup of the deglaciation of North America, big parts of Canada stayed below sea level and were only recovering very slowly.   
In PISM 0.7 parts of Canada were also flooded because of the quick ice retreat in the setup, but recovered much quicker. The Figure below shows the PISM mask at 8ka BP for the same setup, using different model versions. 
![pism_lc_bug](https://user-images.githubusercontent.com/25295341/48546529-e2255200-e8c8-11e8-9e6e-330cd5c439e3.png)

Yesterday I finally found (and fixed) the problem which was a typo in the LC model:  

In `line 298 in src/earth/LingleClark.cc`: 
```step(ice_thickness, sea_level_elevation, dt);``` 
`dt` should be `dt_beddef`, as it was before.

**Comment by ckhroulev** [comment]
@sebhinck Thanks!
