### ISSUE TITLE
Arch Linux package build

### ISSUE THREAD

**Issue by juseg** [pism/pism#426]
PISM builds nicely on top the Arch User Repository's PETSc version, so I've prepared a package build. 

https://aur.archlinux.org/packages/pism/
https://github.com/juseg/pism-pkgbuild

This should build PISM 1.1 and any required dep including PETSc in one go (tested on Manjaro using `pamac build pism`). It installs PISM in `/usr/bin/pismr`, `/usr/lib/libpism.so`, etc. Is someone else using Arch-based Linux who could you help me test it, tell me if it is useful, would do it differently etc?

**Comment by citibeth** [comment]
I use spack to install PISM, it works the same on all Linuxes.  I think
that is more maintainable than special purpose scripts to install pism in
one particular is and version.

Http://spack.io

**Comment by aaschwanden** [comment]
Thank you @juseg for making this work. Here at UAF we only maintain OSX and a Debian/Ubuntu system to test build so we welcome any additions.

We have a GitHub repo, https://github.com/pism/pism-builds, that has build scripts for the systems we maintain --- maybe you would like to add yours here too?

@citibeth I recall you mentioned using spack a while ago and it looks interesting. So far we just never had the manpower to further pursue this.

**Comment by juseg** [comment]
@aaschwanden to be honest the work was mainly done by your team's efforts to make PISM compatible with latest PETSc and GCC. Arch requires a separate git repo. Do you want me to push to pism-builds in parallel? Seems overkill no?

@citibeth Thanks for the feedback. Yes I realize this is limited to one distribution and version.

**Comment by anders-dc** [comment]
The PKGBUILD works well for me (stock Arch) so I added relevant installation instructions to the docs in #438

**Comment by ckhroulev** [comment]
Installing PISM on Arch Linux using `yay` ([`arch.rst`](https://github.com/pism/pism/blob/15d46316bd0512437c861b3d770f74dc11c49319/doc/sphinx/installation/arch.rst)) and installing PISM using Spack on Linux and macOS ([`spack.rst`](https://github.com/pism/pism/blob/3b8f32532a326010af90c3a793129828cde30f2d/doc/sphinx/installation/spack.rst)) are now in the manual.

Also: see `docker/archlinux` and `docker/debian-spack` for `Dockerfiles` that can be used to test this.

I think it's time to close this one.
