### ISSUE TITLE
PISM ERROR: Maximum diffusivity of SIA flow (108.410554 m2/s) is too high.

### ISSUE THREAD

**Issue by jacksd233** [pism/pism#431]
When running PISM for a while, it ends abnormally and says:
``` 
.......
    SSA speed was capped at 1 locations
    SSA speed was capped at 1 locations
    SSA speed was capped at 1 locations
    SSA speed was capped at 1 locations
    SSA speed was capped at 1 locations
    SSA speed was capped at 1 locations
 y  SSA:    16 outer iterations, ~45.8 KSP iterations each
 v$Eh  energy (overrides 2D CFL) (dt=0.02994)
 S     5268.153:    1.01700   15.91040          8.58654 498725.02831
 PISM ERROR: Maximum diffusivity of SIA flow (111.568079 m2/s) is too high.
             This probably means that the bed elevation or the ice thickness is too rough.
             Increase stress_balance.sia.max_diffusivity to suppress this message.
             while updating the stress balance
             while performing a time step. (Note: Model state was saved to "10000_LIS_elaSMB_states_stressbalance_failed.nc".)
```

It seems that `max_diffusivity` is the model output and I don't know how to change `stress_balance.sia.max_diffusivity`

Do you know how to solve this problem?

**Comment by tkleiner** [comment]
This is very good error message as it points directly to the parameter that needs to be changed. See your `src/pism_config.cdl` for details.

One option would be PISM's config_overides mechanism `pismr -config_override config_override.nc ...` with
```
cat <<EOF | ncgen -o config_override.nc
netcdf config_override{
  variables:
  // set 1000.0 m2.s-1. default 100.0 m2.s-1 
  pism_overrides:stress_balance.sia.max_diffusivity = 1000.0;
}
EOF
```

**Comment by jacksd233** [comment]
@tkleiner Thanks for the solution!
But the `max_diffuxivity` of previous results were always below 5 m2/s. I rebuilt PISM recently as the compiler of the server has an update. This test ran correctly previously, but the problem occurs when I run the same test now.

**Comment by talbrecht** [comment]
Yes, SIA diffusivities shouldn't be much larger than 10 m2/s. But there are cases in isolated regions, e.g. for inconsistent data regridding, where diffusivities can grow large and also limit the adaptive timestep length. You can also avoid this with the option `-limit_sia_diffusivity` or by setting `pism_overrides:stress_balance.sia.limit_diffusivity = "yes";`. It is possible that simulation results differ for different computational settings (including compiler), it is a nonlinear system, but it could also indicate inconsistent dependencies. Please double check!

**Comment by tkleiner** [comment]
We got reproducible issues also in the past, especially for -O3 compiler optimization. Option `-fp-model precise` for PISM and PISM's prerequisites (e.g. PETSc) could help as mentioned in the [install manual](http://pism-docs.org/sphinx/installation/pism.html).

I use `-O2 -xHost -fp-model precise -no-fast-transcendentals` without any measurable perfomance drop (16km Antarctica).

**Comment by jacksd233** [comment]
@talbrecht Could you explain the option `-limit_sia_diffusivity`? Using this option can keep sia_diffusivity not too large?

**Comment by jacksd233** [comment]
@tkleiner Could you tell me how to use `-O2 -xHost -fp-model precise -no-fast-transcendentals`? I only find `-fp-model precise` in the pism manual.

**Comment by aaschwanden** [comment]
I would try to set the command line option `-stress_balance.sia.max_diffusivity 1000.0` (or as @talbrecht suggested, overwrite the default value in the config file). 

I find that for short periods of times, the diffusivity can reach very high values (i.e. when doing parameter calibration). Usually, after a few very small time step, the system will adjust and diffusivities drop again. If this doesn't happen it may indeed point to inconsistencies in the model setup.

**Comment by jacksd233** [comment]
@aaschwanden I have tried to increase the `max_diffusivity` to 1000.0 and it works. But the same test previously can run properly with `max_diffusivity 100` fails now due to the max_diffusivity problem. This troubles me a lot.

**Comment by talbrecht** [comment]
Option `-limit_sia_diffusivity` adds an upper bound, defined in `stress_balance.sia.max_diffusivity`, and PISM continues simulations instead of stopping... The CFLAGS and CXXFLAGS mentioned by Thomas should be already set during PETSc installation..

**Comment by jacksd233** [comment]
@talbrecht I see, thank you!

**Comment by jacksd233** [comment]
@talbrecht  It seems that there is something wrong with the boundary and the ice thickness flows from the top boundary to the bottom. I think this leads to the extremely large SIA max_diffusivity. I tried the option -periodicity none to prevent periodic boundary condition but it failed. Do you know how to remove the periodic boundary conditions?

Here is the ice thickness figure:
![Ice_difference_g6](https://user-images.githubusercontent.com/29560723/54619099-7865b200-4a3a-11e9-879f-e7454c5f7b4e.png)

**Comment by talbrecht** [comment]
Yes, that's true. The option `-periodicity none` seems correct and should work. Instead of the option you can use the config-override file. You can alternatively define an `-ocean_kill_file` with topg<0 and vanishing thk along the computational boundary, such that ice flow is forced to calve off there.

**Comment by talbrecht** [comment]
@jacksd233 : Did it work for you now? Can the issue be closed?

**Comment by jacksd233** [comment]
@talbrecht I can use `-thickness_calving` to get a plausibly correct result now. But I still don't know why the result remains to be periodic in `-calving float kill` even with changing the config-override file.

**Comment by talbrecht** [comment]
Did you double-check in the result file with ncdump -h, whether the periodic boolean in piusm_config was actually set correctly?

**Comment by sebhinck** [comment]
As far as I know the option `-periodicity none` only affects the calculation of gradients at the domain margin, but does not prevent ice from leaving the domain on one side and returning on the opposite side.

To remove ice along the margin using the ocean-kill mechanism does prevent ice from wrapping around but also greatly impacts your experiment. Therefore the domain should usually be chosen such that no ice gets close to your margin.

**Comment by bueler** [comment]
Periodicity is a surprisingly hard-to-maintain aspect of PDE-solving software.  It is also hard to communicate to users.  So let me second the point @sebhinck just made, as it applies to all users:

- the computational domain (i.e. the rectangle), and 
- the mass balance near the limits of the computational domain

should be _consciously_ chosen so that no ice gets close to the limits of the computational domain.

Unless, that is, you have a compelling reason to want periodicity.  A compelling reason is that you are e.g. mimicking a intercomparison experiment.  Or your planet is actually a torus.

**Comment by jacksd233** [comment]
@talbrecht Yes, I check the file and it shows 

            pism_config:grid.periodicity = "none" ; 
		pism_config:grid.periodicity_choices = "none,x,y,xy" ;
		pism_config:grid.periodicity_doc = "horizontal gridperiodicity" ;
		pism_config:grid.periodicity_option = "periodicity" ;
		pism_config:grid.periodicity_type = "keyword"

**Comment by jacksd233** [comment]
@sebhinck I see. I will try expanding the computational domain and changing the mass balance near the top boundary.

**Comment by jacksd233** [comment]
@bueler Thanks for the summary!

**Comment by ckhroulev** [comment]
@jacksd233 `grid.periodicity` has very little effect (and should probably be removed or renamed).

It affects

- the diagnostic computation of the driving stress near the edge of the domain,
- the computation of the surface gradient in the SSA code in some very specific case (if `stress_balance.ssa.compute_surface_gradient_inward` is set, i.e. in some synthetic geometry experiments),
- the diagnostic computation of the vertical velocity of ice,
- the diagnostic computation of the (SIA) shear stress component `tauxz`,
- surface gradient near the edges of the domain in the Weertman sliding law,
- the rarely-used FEM implementation of the SSA stress balance.

To add to helpful comments by @sebhinck and @bueler: in simulations where extending the domain or modifying the mass balance near domain boundaries is not appropriate one could try PISM's "regional" mode which adds mechansms limiting the *flow* of the ice near domain boundaries. This usually involves modifications to driving stress computations, limiting sliding, and fixing geometry in a narrow strip along the boundary. (Choosing the right combination of measures usually requires some trial and error, though.)

**Comment by ckhroulev** [comment]
You also mention that
> I rebuilt PISM recently as the compiler of the server has an update. This test ran correctly previously, but the problem occurs when I run the same test now.

Please provide the PISM version you use *whenever you ask about PISM's behavior or a change in PISM's behavior*. In particular, in this case it would be very useful to ensure that tests performed **before** and **after** you rebuilt PISM use the same version of the code.

**Comment by jacksd233** [comment]
@ckhroulev I see, thank you for the reminder. The previous version is `PISM (stable v1.0-35-g9b1b6ff committed by Torsten Albrecht on 2018-03-14 11:04:20 -0800)` and the present version is `stable v1.1.3 committed by Constantine Khrulev on 2019-03-14 10:58:04 -0800`. I should try the old version.

**Comment by jacksd233** [comment]
I test the old version of PISM (v1.0) and everything goes well. I can reproduce previous experiments.  However, other v1.1.x versions of PISM show the same error (` PISM ERROR: Maximum diffusivity of SIA flow is too high.`) and end abnormally. I also test different versions of PETSc and it turns out PETSc has nothing to do with the error. 

So, can I keep using PISM v1.0?

**Comment by talbrecht** [comment]
PISM v1.0 is totally ok if you don't require the updated physics (see CHANGES.rst). But if not the periodicy issues was causing the high SIA diffusivity, we should keep an eye on this issue and see if other users have similar issues with the v1.1.x?!
