### ISSUE TITLE
Howto: Parameter names in pism_config.cdl

### ISSUE THREAD

**Issue by tkleiner** [pism/pism#432]
How should parameters be named in `pism_config.cdl`? 

See e.g. in dev (https://github.com/pism/pism/commit/3d164d4abf8ac68c8428ee07127045b52c625075):

```
pism_config:constants.ice.thermal_conductivity = 2.10;
...
pism_config:energy.bedrock_thermal.conductivity = 3.0;
```
Note the difference between "ice." and "bedrock_" as well as "_conductivity" versus ".conductivity".

Similar in master (https://github.com/pism/pism/commit/761bf059490de2c53e12df35d1e4cfc0d2bc8f48):

```
pism_config:constants.ice.thermal_conductivity = 2.10;
...
pism_config:energy.bedrock_thermal_conductivity = 3.0;
```
Note the slight difference for bedrock thermal conductivity between dev and master.

**Comment by ckhroulev** [comment]
In general PISM's parameter names should have one or more prefixes corresponding to the part of the model controlled by a parameter, followed by a short but descriptive name. Prefixes are separated by periods ("`.`"). This defines a hierarchy of parameters.

Some parameters (mostly physical constants) are used throughout the model; I used the prefix `constants` for these.

Not all names are perfect and I'm happy to change them if it is necessary to avoid confusion.

As for the names you mention, the prefix `energy.bedrock_thermal` could (maybe should) be `energy.bedrock_thermal_layer`, i.e. `energy.bedrock_thermal.conductivity` is the conductivity of the bedrock thermal layer.

I'm cleaning things up as I go -- this is why names in `master` and `dev` are different.

Let me know if this answers your question.
