### ISSUE TITLE
Introduce optional checksums for debugging

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#436]
In recent reproducibility tests (#407) we have used checksum for different model variables to find the timestep at which results diverge (courtesy @maxluebke). We would like to suggest to add checksum-functionality to PISM as compile-time-option to simplify debugging in for similar issues in future. 

For instance, for the enthalpy variable in `src/energy/EnergyModel.cc` this would read as

```
void EnergyModel::printSingleChecksum(const char *prefix, const IceModelVec* source) {
  m_log->message(2, "%s_DEBUG_CHECKSUM_%s: %lx\n", prefix, (source->get_name()).c_str(), source->computeChecksum());
}

void EnergyModel::printChecksumFromVector(const char *prefix, std::vector<double> vec) {
  uint64_t sum = 0;
  for (auto v: vec) { 
    sum += *(uint64_t*) &v;
  }
  m_log->message(2, "%s_DEBUG_CHECKSUM: %lx\n", prefix, sum);
}
```
with 
```
void printSingleChecksum(const char *prefix, const IceModelVec* source);
void printChecksumFromVector(const char *prefix, std::vector<double> vec);

```
in `src/energy/EnergyModel.hh` and called in `src/energy/EnthalpyModel.cc`
```
printChecksumFromVector("Enthalpy_update", Enthnew);
```

In order to have this as option, the functionality could be activated for `#if PISM_DEBUG > 0` in `CMakeLists.txt` with a wrapper like

```
inline void PrintCheckSum(const IceModelVec& v) {
#if PISM_DEBUG > 0
	v->PrintSum(...)
#endif
}
```

This would be a comparably small code change, but it could help for quick checks on reproducibility during runtime.

**Comment by ckhroulev** [comment]
@talbrecht Please see a3d0d6d46944ac053fb613d76a7e679e3fcce2dd.

I added `IceModelVec::checksum()` that computes a [widely-used position-dependent checksum](https://en.wikipedia.org/wiki/Fletcher's_checksum) of data on processor sub-domains and combines results to get one single output for the whole domain.

Use `pism::fletcher64()` to compute checksums of serial 1D vectors.

This should make it much easier to use checksums for debugging.

I don't think we need to add functions you described (`EnergyModel::printSingleChecksum()` and so on): it is better to add throw-away printing code *for a particular debugging task* and remove it later.

**Comment by ckhroulev** [comment]
Please feel free to re-open.
