### ISSUE TITLE
Mismatching prototypes for PETSc < 3.5.0

### ISSUE THREAD

**Issue by citibeth** [pism/pism#442]
This might have been resolved by now.  But in some old version of PISM I'm running, prototypes mismatch:

**SSAFEM.cc:**
```
#if PETSC_VERSION_LT(3,5,0)
PetscErrorCode SSAFEM::jacobian_callback(DMDALocalInfo *info, const Vector2 **velocity,
                                         Mat A, Mat J, MatStructure *str, CallbackData *fe) {
  try {
    (void) A;
    (void) info;
...
```

**SSAFEM.hh:**
```
#if PETSC_VERSION_LT(3,5,0)
  static PetscErrorCode jacobian_callback(DMDALocalInfo *info,
                                          Vector2 const *const *const xg,
                                          Mat A, Mat J, MatStructure *str,
                                          CallbackData *fe);
```
I resolved the issue by switching to PETSc 3.5.  (PETSc 3.9 doesn't work with this version for some other reason).

**Comment by ckhroulev** [comment]
> I resolved the issue by switching to PETSc 3.5.

This is what I would have recommended.

Note that PISM no longer supports PETSc < 3.5 (see https://pism-docs.org/sphinx/installation/prerequisites.html) and there is no mismatch in the current code, so this is no longer relevant.

**Comment by citibeth** [comment]
If <3.5 is no longer supported you can remove the ifdefs?

**Comment by ckhroulev** [comment]
Yes, you can remove `#if PETSC_VERSION_LT(3,5,0)` in the branch you are working with (they are already gone in the current code).

This is what I see when I search for `PETSC_VERSION` in `dev`:
```
./inverse/IPTaoTikhonovProblem.hh:356:#if PETSC_VERSION_LT(3,7,0)
./util/IceGrid.cc:866:#if PETSC_VERSION_GE(3,8,0)
./util/Profiling.cc:36:#if PETSC_VERSION_LE(3,6,3)
```

**Comment by ckhroulev** [comment]
Please re-open if you think that this is still relevant.
