### ISSUE TITLE
Tillwater changes when ice is advected to ocean areas.

### ISSUE THREAD

**Issue by jacksd233** [pism/pism#446]
Dear PISM masters, We noticed that when ice is advected to a grid point that was ocean-covered, the till water content is immediately set to zero or close to zero, and starts growing then due to melting etc. It seems that in reality, the till in an ocean-covered point would be saturated. Wouldn't it make sense to initialize the till at such a point as being saturated (say maximum till water content of 2m)? Regardless of the current model default settings, do you mind writing how I could implement such a change myself to test its effects? Many thanks! Weiwen

**Comment by talbrecht** [comment]
Hej Weiwen, I agree that this should be the default, see #425. But this can have a strong influence on grounding line stability, similar to option -tauc-slippery_grounding_line, as shown in paleo simulations (see https://www.the-cryosphere-discuss.net/tc-2019-71/).
