### ISSUE TITLE
Bug in Timeseries

### ISSUE THREAD

**Issue by sebhinck** [pism/pism#448]
I have just discovered a bug in the calculation of the piecewise-linear interpolation of a timeseries (`src/util/Timeseries.cc` line 241), which was introduced with commit a12247754b89c847a016bc79598e9b9163dc087c).
![timeseries_bug](https://user-images.githubusercontent.com/25295341/72379953-b728cf00-3714-11ea-8418-18a506737269.png)
The figure shows the original SL forcing (black) and how it is interpolated by PISM (red).

The above mentioned line should read the following:
```C++
return m_values[k+1] * alpha + m_values[k] * (1.0 - alpha);
```
(the indices `k` and `k+1` are swapped!)

**Comment by ckhroulev** [comment]
This is embarrassing. (Thanks for the bug report!)

I believe this issue should be fixed now.

**Comment by sebhinck** [comment]
Ok, I'll close it then! Thanks for the correction!
