### ISSUE TITLE
Linear interpolation of periodic IceModelVecT forcing fields

### ISSUE THREAD

**Issue by sebhinck** [pism/pism#449]
I just discovered another problem that was recently introduced into the dev branch (61184e83e1579710daafa7070d039c6318d87d61):

My runs were crashing shortly after starting with this Error message:
`PISM ERROR: invalid interval: (28596378.569336, 285867.129517)`

This is the setting when the error occurs:   
Allocation of the Forcing field:
```
m_T0 = IceModelVec2T::ForcingField(m_grid,
                                   file,
                                   "airtemp_0",
                                   "", // no standard name
                                   buffer_size,
                                   evaluations_per_year,
                                   periodic,
                                   LINEAR);
```
Initialization of the field (monthly data, periodicity of one year):
```
m_T0->init(opt.filename, 1, 0.0);
```
Updating the field:
```
m_T0->average(t, dt);
```

I could trace back the error to `Interpolation::init_weights_linear`. The function assumes the requested times to be increasing. This unfortunately is not the case for periodic fields.

I could overcome this issue by setting the `InterpolationType` to `PIECEWISE_CONSTANT`, instead of `LINEAR`.

Probably this should be handled differently...

**Comment by ckhroulev** [comment]
@sebhinck Have you tried using `LINEAR_PERIODIC` instead of `LINEAR`?

Also, see `test_linear_periodic()` in [`test/miscellaneous.py`](https://github.com/pism/pism/blob/5a962f8/test/miscellaneous.py#L1081). This test should (I hope it does, anyway) ensure that periodic linear interpolation works correctly.

**Comment by sebhinck** [comment]
@ckhroulev  No, I haven't tried to use `LINEAR_PERIODIC`, because it is set automatically when `periodic==TRUE`. 

But I just realized that there is an inconsistency in my code, so that the `period` read from the configuration using `ForcingOptions` was actually meant for another variable in that file (which is not periodic). Therefore in the example above `periodic=FALSE`....

Sorry for the confusion. I will close this issue!

**Comment by ckhroulev** [comment]
> ... because it is set automatically when `periodic==TRUE`

Ah. I forgot about that...
