### ISSUE TITLE
How to use an elevation-dependent mass balance forcing changing with time?

### ISSUE THREAD

**Issue by jacksd233** [pism/pism#450]
Hello,
   I want to use an elevation-dependent mass balance forcing that changes with time, which means as the model runs, the elevation-dependent mass balance will change slowly instead of being constant. It seems that I need to add a "time" variable to the "Elevation.cc" lies in "/src/coupler/surface". Do you know how to change the source codes to achieve this?

Best regards.

**Comment by talbrecht** [comment]
We are on the way to merge code that scales precipitation or surface mass balance with respect to elevation change using an exponential formulation similar to relative changes in forcing temperature, see #416. Would this help?

**Comment by jacksd233** [comment]
@talbrecht Sorry for not making it clear. My question is more about time-dependent, not elevation dependent. My question will then be how to get the model time. Seems like there is a variable `m_time` but I don't know which header file I should include to use it.

**Comment by ckhroulev** [comment]
> My question will then be how to get the model time.

The class `pism::surface::Elevation` has a method called `update_impl()`. This is what's called when PISM needs to ask `pism::surface::Elevation` to update its state. The arguments `t` and `dt` of `update_impl()` define the requested time interval: `[t, t + dt]`. Both `t` and `dt` are in seconds.

You would have to pass `t` (and possibly `dt`) to your code computing the mass balance.

**Comment by jacksd233** [comment]
@ckhroulev That's exactly what I want. Thanks!
