### ISSUE TITLE
How to use -extra_split to save separate files?

### ISSUE THREAD

**Issue by jacksd233** [pism/pism#453]
Hi,
   I am running a long simulation and I want to save spatially-varying diagnostic quantities to separate files. For example, I will run a 500000 years simulation and I want to save the output as ex_0yto100000y.nc, ex_100000yto200000y.nc, ex_200000yto300000y.nc, ex_300000yto400000y.nc, and ex_400000yto500000y.nc. Could you tell me how to do this this with -extra_split or other codes?

Best regards.

**Comment by talbrecht** [comment]
This extra split command will give you 5 files every 100000 years: `-extra_file filename.nc -extra_times 0:500000:100000 -extra_vars thk -extra_split`, but I guess this is not what you want? Otherwise, you could also use cdo or nco tools to split or concatenate files.

**Comment by jacksd233** [comment]
@talbrecht Well, this command gives me 5 files with only one time output. I need each file to output every 100 years. Like 0:100:100000; 100000:100:200000...

**Comment by talbrecht** [comment]
exactly, then you should use cdo or nco to split or concatenate the files in 5 chunks.

**Comment by jacksd233** [comment]
I see, thank you!

**Comment by aaschwanden** [comment]
As @talbrecht pointed out, you can merge/concatenate files to your liking with CDO in post processing. Alternatively, you could stop a simulation very 1M years and then restart. `-extra_split` would not be needed then.

@jacksd233: I recommend asking these kinds of questions via our new Slack channel.

**Comment by jacksd233** [comment]
Got it. By the way, does PISM have any options to automatically stop and restart?

**Comment by ckhroulev** [comment]
> ... does PISM have any options to automatically stop and restart?

No, it does not.

**Comment by jacksd233** [comment]
I see, thanks for the answers! I am going to close this issue.

**Comment by citibeth** [comment]
For what it's worth... I have a main program that links to PISM
programmatically and starts / stops / restarts it.

-- Elizabeth

**Comment by jacksd233** [comment]
@citibeth Oh, could you show me the codes?
