### ISSUE TITLE
Don't limit maximum speeds

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#455]
I suggest to change the default value of `stress_balance.ssa.fd.max_speed` to something near infinity. Capping SSA velocities, IMHO, is not a good idea because the implications on the disrectized equations, and by extension, on the resulting ice flow, are not understood. 

Occurrences of un-physically high speeds are generally short lived. What this all means I am not sure, but my guess it tells us that ice flow is happening in a way that is not captured by PISMs ice flow dynamics. PISM's solver does the right thing and shortens the time step until the inconsistency is "diffused away" by the diffusive nature of ice flow.

The motivation for this suggested changes comes from several runs that break with 

```
PISM WARNING:  KSPSolve() reports 'diverged'; reason = -11 = 'DIVERGED_PCSETUP_FAILED'
  writing linear system to PETSc binary file SSAFD_kspdivergederror.petsc ...
  re-trying using the Additive Schwarz preconditioner...
PISM WARNING:  KSPSolve() reports 'diverged'; reason = -11 = 'DIVERGED_PCSETUP_FAILED'
  writing linear system to PETSc binary file SSAFD_kspdivergederror.petsc ...
PISM ERROR: SSAFD KSP (linear solver) failed: DIVERGED_PCSETUP_FAILED
            while updating the stress balance
            while performing a time step. (Note: Model state was saved to 'g5000m_id_E3-4_0_10000_stressbalance_failed.nc'.)
```

If I increase `stress_balance.ssa.fd.max_speed` to `10e6 m/yr`, the simulations work.

While this anecdotal evince, I suggest the deactivate poorly understood mechanisms such as capping SSA speeds by default.

**Comment by ckhroulev** [comment]
I agree that `stress_balance.ssa.fd.max_speed` should have the default value high enough to disable this mechanism. Our experience shows that the current default (500 km/year) is not high enough.

**Comment by talbrecht** [comment]
I have actually introduced the cap for the relatively artificial model spin-up with `-no-mass` but with applied SSA stress balance. In such a case there is no diffusional effect and the adaptive time steps gets locked. Hence I would support to have an optional cap or a default value as high as the speed of light or so, which certainly should be a hard physical bound.

**Comment by ckhroulev** [comment]
> Hence I would support <...> a default value as high as the speed of light <...>

Great!
