### ISSUE TITLE
Use high basal yield stress in "ice-free ocean" areas

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#456]
This is an issue I discovered while debugging a SSA solver failure (related: #455).

In `IceModel::step()` PISM has to estimate the ice velocity *before* it can update any of PISM's time-stepping sub-models (i.e. sub-models using the current model time and the time step length in any way). In the current code the yield stress model is a time-stepping model, so it has to be updated after the stress balance computation.

This means that the stress balance code uses the basal yield stress from the previous time step. This yield stress field may be inconsistent with the ice geometry. Some inconsistencies have little effect; others may cause a failure of the SSA solver.

In a case I was looking at a couple of cells were ice-free with the bed barely below sea level during one time step and icy and grounded during the next time step. Moreover, these cells were *not* connected to the rest of grounded ice (i.e. formed a small "ice cap"). This resulted in a SSA solver failure because this "ice cap" was essentially an "iceberg": isolated and with no basal drag because of the inconsistent (and zero) basal yield stress from the previous time step.

I propose changing the code in `MohrCoulombYieldStress::update_impl(...)` from

``` c++
    if (cell_type.ocean(i, j)) {
      m_basal_yield_stress(i, j) = 0.0;
    } else if (cell_type.ice_free(i, j)) {
      m_basal_yield_stress(i, j) = high_tauc;  // large yield stress if grounded and ice-free
    } else { // grounded and there is some ice
      // more code here
    }
```
to
``` c++
    if (cell_type.ice_free(i, j)) {
      m_basal_yield_stress(i, j) = high_tauc;  // large yield stress if ice-free
    } else { // grounded and there is some ice
      // more code here
    }
```
This would not eliminate inconsistencies (this is a fundamental issue) but *should* reduce their effect.

If I hear no objections I will make this change and close this issue next week.

**Comment by talbrecht** [comment]
I think I observed similar issues, but quite rare. Underneath the ice shelves, which belong to `cell_type.ocean(i, j), m_basal_yield_stress` should be set to 0 at some point?!

**Comment by ckhroulev** [comment]
> Underneath the ice shelves, which belong to `cell_type.ocean(i, j)`, `m_basal_yield_stress` should be set to 0 at some point?!

This should not be necessary: the basal yield stress is not used in "floating" areas.
