### ISSUE TITLE
FindPETSc() Test Fails on some HPC Systems

### ISSUE THREAD

**Issue by citibeth** [pism/pism#457]
**Description**

The FindPETSc() test compiles a "hello world" PETSc program, and then tries to run it.  This causes problems on certain systems in which MPI programs cannot be run directly on login nodes --- either with the mpirun command or directly.  See here for more details:

https://github.com/pism/pism/commit/101ab4a85a0d87b9b2918cc898462addb34a9a28

**PISM version**

OLD PISM version; might no longer be relevant.

**Comment by ckhroulev** [comment]
This is a known issue: see [Common build problems and solutions](http://pism.github.io/pism/installation/common-problems.html) in the manual.

Setting `PETSC_EXECUTABLE_RUNS` like this

```
  cmake -DPETSC_EXECUTABLE_RUNS=1 [other options]
```

should make it possible to build PISM on systems in which login nodes cannot run code compiled for compute nodes (including systems that require cross-compilation).

**Comment by ckhroulev** [comment]
Superseded by #476.
