### ISSUE TITLE
Add regularized Coulomb sliding law

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#459]
Reference: Zoet and Iverson, 2020 (http://doi.org/10.1126/science.aaz1183)

PISM considers both effects of form drag (pseudo plastic sliding law with slip rate u_b) vs. skin friction (Mohr Coulomb friction with dependence on effective pressure) and results in a smooth transition between Weertman-style sliding (slow) and Coulomb plasticity (fast ice streams). Zoet and Iverson, 2020 present the combination in terms of a **"regularized Coulomb sliding law"** (Eq. 3, similar to Schoof 2005), meaning that plastic deformation states the upper limit for high sliding speeds (see plots in [https://nbviewer.jupyter.org/url/www.pik-potsdam.de/~albrecht/notebooks/compare_pism_regularized_sliding.ipynb](https://nbviewer.jupyter.org/url/www.pik-potsdam.de/~albrecht/notebooks/compare_pism_regularized_sliding.ipynb)).

There is also a threshold velocity (40-80 m/yr), which seems similar to the PISM's default value of 100m/yr (but product instead of sum). The exponent p=5 corresponds to PISM's pseudo plastic q=0.2. Another difference between both approaches is the effective pressure definition. While in Zoet and Iverson, 2020 it is the classical difference between overburden and pore water pressure N=Po-P used for modeling cavity closure, this is distinct from N_till in PISM, which is explained by the very low hydraulic conductivity of till. In fact, for tillwat=2 both are equal N=delta*Po. 

For a better comparison and evaluation it would be worthwhile to implement this new version of a sliding law as additional option into PISM. But this feature request post is also open for discussions... Another good comparison can be found here: https://doi.org/10.1017/jog.2017.51

**Comment by bueler** [comment]
I saw Zoet and Iverson 2020 and was curious about the difference.  Thanks for completely answering my curiosity.  I agree it is worth implementing in PISM.

I have taken the liberty of putting the graphs you generated here, for quick reference:

![foo](https://user-images.githubusercontent.com/1103951/80152544-55c09980-8568-11ea-8c37-0459463a245a.png)

**Comment by bueler** [comment]
The implication is that there ought to be more fast sliding, right?  Or maybe more abrupt, and less diffuse, onset of sliding?  Can't wait to see the runs!

**Comment by aaschwanden** [comment]
I've glanced over the paper a couple of weeks ago and I agree it would be an interesting comparison. Given the similarities, as pointed out by @talbrecht, I would expect a similar performance than our current implementation. 

@talbrecht: if you have the time, feel free to go ahead with the implementation. We'd be happy to assist but we currently don't have the resources to take the lead (Constantine is working on a higher order solver at the moment).

**Comment by talbrecht** [comment]
Yes, this can make quite a difference.
Regarding the plots I would add the assumed values for ice thickness (1000m), tillwater (2m), delta (2% default) and till friction angle (30°), all other values are PISM defaults.

**Comment by talbrecht** [comment]
Interesting display at EGU right now: https://meetingorganizer.copernicus.org/EGU2020/EGU2020-18968.html
