### ISSUE TITLE
Questions about file names

### ISSUE THREAD

**Issue by rersnow** [pism/pism#464]
When I repeated the examples/std-greenland experiment, I found that there are three types of file names: `xxx_backup.nc` 　 `xxx_backup.nc~` and `xxx.nc`.

What is the difference between the three different file naming methods? I did not find the correct documentation to solve this problem, and it troubled me for a long time. If you know, please help me to solve this problem, thank you for your help!

**Comment by ckhroulev** [comment]
If you run PISM with the command-line option `-o xxx.nc` it will save the state of the model _at the end_ of the simulation to the file named `xxx.nc`.

In addition to this, PISM has the ability to periodically save the state of the model _during_ a long simulation. By default it does that every hour (regular "wall-clock" time, not model time), saving it to `xxx_backup.nc`. These backups can be used to re-start a long simulation if it gets interrupted for some reason 

For example: if your simulation runs out of wall clock time on a HPC system you can re-start from a backup file. If PISM saves backups every hour you lose at most one hour's worth of computation.

Please see [Saving re-startable snapshots of the model state](https://pism-docs.org/sphinx/manual/practical-usage/saving-snapshots.html?highlight=backup_interval) in the manual for more.

Also, whenever PISM discovers that a file it needs to write to already exists, it moves the original file aside by appending `~` to its name. This is done to avoid losing data by overwriting files by accident.

So, here's what must have happened:

1. A simulation ran for one hour and PISM wrote the model state to `xxx_backup.nc`.
2. The same simulation continued running for another hour. PISM tried to save another backup to `xxx_backup.nc`, but that file already exists: it was created in step 1. This old backup got moved to `xxx_backup.nc~` and the new one got written to `xxx_backup.nc`.
3. The simulation completed and PISM wrote the model state to `xxx.nc`.

Once a simulation is complete you can remove files named `xxx_backup.nc` and the ones that have names ending in `~`.

**Comment by rersnow** [comment]
Thank you very much for your clarification. The explanation is very clear and detailed.Now I have understood the difference between the names of the three documents.
Thanks again for your help!
| |
高凡
|
|
gaof043@163.com
|
签名由网易邮箱大师定制
On 9/5/2020 01:37，Constantine Khrulev<notifications@github.com> wrote：

If you run PISM with the command-line option -o xxx.nc it will save the state of the model at the end of the simulation to the file named xxx.nc.

In addition to this, PISM has the ability to periodically save the state of the model during a long simulation. By default it does that every hour (regular "wall-clock" time, not model time), saving it to xxx_backup.nc. These backups can be used to re-start a long simulation if it gets interrupted for some reason

For example: if your simulation runs out of wall clock time on a HPC system you can re-start from a backup file. If PISM saves backups every hour you lose at most one hour's worth of computation.

Please see Saving re-startable snapshots of the model state in the manual for more.

Also, whenever PISM discovers that a file it needs to write to already exists, it moves the original file aside by appending ~ to its name. This is done to avoid losing data by overwriting files by accident.

So, here's what must have happened:

A simulation ran for one hour and PISM wrote the model state to xxx_backup.nc.
The same simulation continued running for another hour. PISM tried to save another backup to xxx_backup.nc, but that file already exists: it was created in step 1. This old backup got moved to xxx_backup.nc~ and the new one got written to xxx_backup.nc.
The simulation completed and PISM wrote the model state to xxx.nc.

Once a simulation is complete you can remove files named xxx_backup.nc and the ones that have names ending in ~.
