### ISSUE TITLE
Input data of Ross case

### ISSUE THREAD

**Issue by rersnow** [pism/pism#472]
Hello! When I was repeating the ross case(examples/ross/preprocess.py) recently, I entered the ice velocity data as MEaSUREs InSAR-Based Antarctica Velocity Map v2, but the following problems occurred when reading the data:

ncrename: WARNING "grid_mapping" attribute for variable /CNT is type NC_STRING, not NC_CHAR. This violates the CF convention for specifying additional attributes. Therefore nco_xtr_cf_var_add() will skip this attribute. If you want CF to support NC_STRING attributes, please tell them and CC: NCO.

ncrename: ERROR Required dimension 'nx' is not present in input file. HINT: If presence is intended to be optional, then prefix old dimension name with the period character '.', i.e., 'ncrename -d .nx,x'. With this syntax ncrename would succeed even if no such dimension is in the file.

May I ask if you can provide the v1 version?  I want to see what is the difference between the two versions of the data format, so that the 2 data can be modified and run smoothly. Or do you have any good opinions on how to solve the above problems, thank you for your help.

**Comment by talbrecht** [comment]
Hello rersnow,

in the Ross example the preprocessing script points to an older version (900m) of the NSIDC-0484 dataset (reference: http://doi.org/10.1126/science.1208336), which does not seem available any more. The error you see relates to the command 

`ncrename -d nx,x -d ny,y -O antarctica_ice_velocity_900m.nc antarctica_ice_velocity_900m.nc`

as the original dataset came with nx,ny as dimensions. I'll update the script as soon as possible...

Now there is a 450m resolution version avalaible (https://nsidc.org/data/nsidc-0484), see also https://github.com/pism/pism-ais/blob/master/vel_mouginot19/preprocess_netcdf.py

But there is also an older dataset on 1000m resolution (NSIDC-0720), see https://nsidc.org/data/measures/aiv for an overview and download links. Which is the one you would like to compare to?

**Comment by talbrecht** [comment]
Maybe this helps: https://github.com/pism/pism/commit/7752677c0c8ec4253d1c167c510d26f3d76760f2

**Comment by rersnow** [comment]
Hello  talbrecht,

I am honored to receive your help and suggestions.

I would like to use the 450m resolution version available which I have downloaded from NSIDC several days ago. Then I will repeat this experiment with the modified script and try to solve this problem.

Thanks very much.
