### ISSUE TITLE
How to convert units in SSA

### ISSUE THREAD

**Issue by y624745579** [pism/pism#473]
**Description**

Hello, when I  was doing ROSS ice shelf simulation in Antarctia using SSA according to PISM Manual, but I found the unit output 
 velocity u_ssa and v_ssa is m/s, its value is very small on the order of 10e-6 and the result figure is diffrent from  the manual , how can I modify the unit in PISM to m/y just like the observe value u_ssa_bc and v_ssa_bc. Thank you very much.

**PISM version**

PISMR (basic evolution run mode) stable v1.2.2
PISM (stable v1.2.2)

**To Reproduce**

pismr -i ../Ross_combined.nc -bootstrap -Mx 211 -My 211 -Mz 3 _lz 3000 -z_spacing equal -surface given -stress_balance ssa -energy none -no_mass -yield_stress constant -tauc 1e6 -pik -ssa_dirichlet_bc -y 1.0 -ssa_e 0.6 
../plot.py diag_Mx211.nc

**Comment by talbrecht** [comment]
Dear @y624745579 ,

yes, PISM is using SI units (as CF standard), but it also understands glaciological units using UDUNITS (see last paragraph in https://pism-docs.org/sphinx/technical/cf-standard-names.html). 
So, when you plot the netCDF data, you can simply multiply the SSA velocities with seconds_per _year = 60*60*24*356 for a `time:calendar = "365_day"`, see https://github.com/pism/pism/commit/7752677c0c8ec4253d1c167c510d26f3d76760f2 for instance. 
You could also manipulate the PISM output data with NCO tools:
```
ncap2 -O -s 'u_ssa*=30758400;v_ssa*=30758400' diag_Mx211.nc diag_Mx211_myear.nc
ncatted -O -a units,u_ssa,o,c,"m year-1" -a units,u_ssa,o,c,"m year-1" diag_Mx211_myear.nc
```
If this helps, just close the issue.
Best, 
Torsten

**Comment by y624745579** [comment]
@talbrecht  Thank you very much!
