### ISSUE TITLE
EISMINT II experiment shows 0.0 max_hor_vel at stdout

### ISSUE THREAD

**Issue by bueler** [pism/pism#477]
**Description**

I ran `./pisms -eisII A -Mx 61 -My 61 -Mz 61 -Lz 5000 -y 5000`.  In the NC output file the max surface velocity was 53 m a-1.  But the max_hor_vel column was all zeros.  That column remains zero for all runs I did.

**PISM version**

Please include the output of `pismr -version` or the output of `git describe --always` (executed in PISM's source code directory).
```
$ ./pismr -version
Petsc Development GIT revision: v3.14.4-701-g235129d795  GIT Date: 2021-02-26 21:42:32 +0000
       The PETSc Team
    petsc-maint@mcs.anl.gov
 https://www.mcs.anl.gov/petsc/
See docs/changes/index.html for recent updates.
See docs/faq.html for problems.
See docs/manualpages/index.html for help. 
Libraries linked from /home/bueler/petsc/linux-c-dbg/lib
----------------------------------------
Reading configuration parameters (pism_config) from file '/home/bueler/pism/build/pism_config.nc'.
PISMR (basic evolution run mode) development 711dd320b committed by Constantine Khrulev on 2021-03-01 13:22:29 -0900
PISM (development 711dd320b committed by Constantine Khrulev on 2021-03-01 13:22:29 -0900)
CMake 3.16.3.
Petsc Development GIT revision: v3.14.4-701-g235129d795  GIT Date: 2021-02-26 21:42:32 +0000
PETSc configure: --with-debugging=1 --download-mpich
MPICH Version:	3.3.2
MPICH Release date:	Tue Nov 12 21:23:16 CST 2019
MPICH ABI:	13:8:1
MPICH Device:	ch3:sock
MPICH configure:	--prefix=/home/bueler/petsc/linux-c-dbg MAKE=/usr/bin/make --libdir=/home/bueler/petsc/linux-c-dbg/lib CC=gcc CFLAGS=-fPIC -fstack-protector -g3 AR=/usr/bin/ar ARFLAGS=cr CXX=g++ CXXFLAGS=-fstack-protector -g -fPIC FFLAGS=-fPIC -ffree-line-length-0 -g FC=gfortran F77=gfortran FCFLAGS=-fPIC -ffree-line-length-0 -g --enable-shared --with-pm=hydra --disable-java --enable-fast=no --enable-error-messages=all --with-device=ch3:sock --enable-g=meminit
MPICH CC:	gcc -fPIC -fstack-protector -g3   -O0
MPICH CXX:	g++ -fstack-protector -g -fPIC  -O0
MPICH F77:	gfortran -fPIC -ffree-line-length-0 -g  -O0
MPICH FC:	gfortran -fPIC -ffree-line-length-0 -g  -O0
NetCDF 4.7.3 of Jan 23 2020 04:18:16 $.
FFTW fftw-3.3.8-sse2-avx.
GSL 2.5.
```

**To Reproduce**

See above

**Expected behavior**

See above

**Additional context**

None needed

**Comment by bueler** [comment]
On a closely-related topic, the table of EISMINT II runs should be updated to indicate that the exp G and H runs will error-out.  (Reported by Kevin Hank.)

**Comment by bueler** [comment]
In this page: https://pism-docs.org/sphinx/manual/simplified-geometry/eismint-2.html

**Comment by ckhroulev** [comment]
The run `./pisms -eisII A ...` *correctly* computes and reports a quantity... but here's the thing: `max_hor_vel` in `stdout` is misnamed, probably for historical reasons.

Its actual meaning is "the maximum magnitude of `u` and `v` components of the basal ice velocity". This is the right quantity to consider when thinking about the maximum time step of the mass continuity equation (and the CFL condition) in the "hybrid" model but I don't know how to describe it concisely. Note that it is not the same as "max. sliding speed" or "max. basal speed".

**Comment by bueler** [comment]
Is there any reason not to have `pisms -eisII` correctly report the max_hor_vel from the SIA?

**Comment by ckhroulev** [comment]
> Is there any reason not to have `pisms -eisII` correctly report the max_hor_vel from the SIA?

There is no reason I can think of, other than the lack of time needed to implement this. :-/

Plus there's the issue of the meaning of `max_hor_vel` reported by PISM.

**Comment by ckhroulev** [comment]
I renamed `max_hor_vel` and explained its meaning in the manual (see e0df9ea9f and 1faf9798b).

I mentioned that sliding EISMINT II experiments are not supported (see 694e513a6).
