### ISSUE TITLE
Update "Simplified geometry experiments" manual pages to show Blatter ISMIP-HOM results

### ISSUE THREAD

**Issue by bueler** [pism/pism#478]
I think the title covers it.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: I'm always frustrated when [...]

**Describe a solution you would like to have**

**Describe alternatives you've considered**

**Additional context**
Please describe the context of the feature outlined above.

**Comment by ckhroulev** [comment]
http://pism.github.io/pism/manual/simplified-geometry/ismip-hom.html
