### ISSUE TITLE
Questions about the basal sliding law

### ISSUE THREAD

**Issue by rersnow** [pism/pism#484]
Hello everyone,

I have three questions about **the basal sliding law** and looked for a lot of meterials but couldn't solve them. Would you like to take a moment to answer my questions? Thanks for your time.

![2021-05-20 10-07-30](https://user-images.githubusercontent.com/70734383/118912143-e9c28780-b959-11eb-90fb-d5011db37af6.png)

1. For this formula, many papers simply explain the relationship between **the exponential q and plasticity**, such as where q = 0 is purely plastic sliding, and q = 1 is sliding linearly related to the applied stress and so on. But I would like to have a more detailed analysis, for example, as the value of q increases, how does the plasticity of the ice change? is it prone to deformation? and what is the effect on the sliding velocity?

2.The **u threshold value** is 100m/a, but the flow velocity near the **ice shelf** mostly exceeds this value. Is the sliding law applicable in these areas? After all, the basal shear stress varies with q when the velocity exceeds 100 and when it does not exceed 100.

3. What does the **minus** sign on the right side of the equation mean? **The magnitude or the direction**? We know that if the basal shear stress is  -1 and -100, if it's the direction, the later is high; If it's magnitude, then the former has a lot of resistance. The results were completely different.

Thank you very much again for your  cooperation.

**Comment by talbrecht** [comment]
Dear @rersnow,
I am not sure if I understand your first question, but in this PISM formulation, one have to keep in mind, that sliding velocities are both input and output. It is an iterative process optimizing for ice velocities assuming this sliding relationship. You can find some sensitivity tests for q variation in Antarctic paleo simulations in https://doi.org/10.5194/tc-2019-71. In fact, the Coulomb yield stress formulation for tau_c assumes near plastic sliding, but I found best fit to observations for q~0.5-0.75.
The u_threshold defines the onset of ice stream flow, here the magnitude of tau_b equals tau_c, but it lowers basal shear stress for values below and scales it above this value. Hence, it applies also for much faster flow, where basal shear stress becomes larger than tau_c for q>0. 
The minus sign indicates the direction of the basal shear stress, opposing the ice flow. It is not a scalar but a vector (bold). You can also use different sliding laws in PISM, check also teh dev branch: https://github.com/pism/pism/issues/459.

**Comment by rersnow** [comment]
Dear @talbrecht,

Thank you for telling me that this is an iterative optimization formula so that many of my puzzles can be solved. Also thanks for providing the article and the teh dev branch, I believe that through them I could gain a deeper understangding of the subglacial progress.
