### ISSUE TITLE
Update regression tests based on verification tests

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#5]
PISM's regression tests based on verification tests should compare convergence rates to stored values instead of comparing numerical errors to stored values.

**Comment by ckhroulev** [comment]
Or maybe they should not.

My original thinking was that our current tests are more "fragile" than they should be, i.e. may fail even though the new code is just as good as the old one in terms of the rate of convergence of a numerical method.

Now I think that **fragile is good**: a regression test should be able to detect *any* change, even a small one.

**Comment by bueler** [comment]
Cool.  I mostly am happy you have an opinion ... and I agree too.
