### ISSUE TITLE
OpenMPI problem: PISM ERROR: Ice thickness exceeds the height of the computational box 

### ISSUE THREAD

**Issue by lcebaman** [pism/pism#505]
When running with OpenMPI we get the following error, however it does not happen with IntelMPI. Is this a well known error?
```
PISM ERROR: Ice thickness exceeds the height of the computational box (6000.0000 m).
            The model state was saved to './results/paleo_16km_max_thickness.nc'. To continue this simulation,
            run with
            -i ./results/paleo_16km_max_thickness.nc -bootstrap -regrid_file ./results/paleo_16km_max_thickness.nc -allow_extrapolation -Lz N [other options]
            where N > 6000.0000.
```

**Comment by aaschwanden** [comment]
@lcebaman : this is not an `OpenMPI` error per se, it just means that the ice thickness is exceeding the computational domain.

Why the ice thickness is getting too large can only be diagnosed with additional information, it is mostly likely the result of modeling choices, and not a bug in PISM. To better help you, I suggest to connect with us on our [Slack channel](https://join.slack.com/t/uaf-pism/shared_invite/enQtODc3Njc1ODg0ODM5LThmOTEyNjEwN2I3ZTU4YTc5OGFhNGMzOWQ1ZmUzMWUwZDAyMzRlMzBhZDg1NDY5MmQ1YWFjNDU4MDZiNTk3YmE).

**Comment by talbrecht** [comment]
Dear Luis, which PISM version do you use? I find this error from time to time in the latest PISM version (2.0.x) using intelMPI, when using `-bed_def lc`. I find only one too thick cell near the grounding line and just cut it off (ncap2) and restart. We are not sure yet, why this happens, as it cannot be easily reproduced. I don't think it is related to intelMPI vs. openMP.
