### ISSUE TITLE
How can i use glacial index in atmospheric component？

### ISSUE THREAD

**Issue by zyastc213** [pism/pism#510]
#atmosphere=" index  -atmosphere_index_climate_file  ${inclim}  -atmosphere_index_index_file ${inindex}   -temp_lapse_rate  0   -precip_decay_rate  0.75  -precip_thresh_height  0  "

the script above is used in pism 0.7 from others. But when i search it in the manual for version 2.0 , i cant find such usage like 'index'. if it is removed in pism 2.0.

**Comment by ckhroulev** [comment]
I'm guessing that you used a modified version of PISM 0.7. `-atmosphere index ...` is not implemented in PISM 0.7 or any other version I know of.

**Comment by aaschwanden** [comment]
I'm closing this issues. If this is still relevant, please open a feature request.
