### ISSUE TITLE
PISM ERROR:  stress balance computation failed. Model state was saved to '*_out_pism_stressbalance_failed.nc'

### ISSUE THREAD

**Issue by zyastc213** [pism/pism#513]
first (x) equation in the SSAFD system: zero diagonal entry at a regular (not Dirichlet B.C.)  location: i =175,j =128
PISM ERROR: ### Rank 35 massage ends here

and then such errors appear in Rank 53..100..102.. 116.. 118.. 120.. message

it is a modified 0.7 version, i dont know whether the reason of error is the same as  the offical version

**Comment by tkleiner** [comment]
This reminds me of issue #349. Fixed Jan 2017.

**Comment by ckhroulev** [comment]
@zyastc213 I'm sorry, but we don't have the resources to address issues in PISM versions as old as 0.7.
