### ISSUE TITLE
SSAFD KSP (linear solver) failed

### ISSUE THREAD

**Issue by eleeice** [pism/pism#514]
Hi all,

I sent this in an email, before realising I could post it here. I hope this is easier for you all. 

Over the past year I have been using PISM on my home PC within a virtual machine. This was an older version of PISM, 1.2 I think. I have recently moved on to my universities HPC that has PISM 2.0.2 on it. It works and has had other people use PISM and successfully modelled glacial ice - primarily at ice-sheet scales. I am modelling a glacial valley in Peru. Other glacial valleys have been successfully modelled successfully using PISM so I am sure I am not using it in an incorrect manner.

When running the model on my VM it runs to completion perfectly fine. I transferred all the files I needed onto the HPC, updated the spin.sh script to allow it to run on the HPC, ran it, expecting to see an similar result to what I had run before, but it kept crashing and terminating out. It would not even go past the first 100 years. Below is a extract from the out file that details the issue.

```
vy$Eh  diffusivity (overrides energy) (dt=1.93275 in 8 substeps; av dt_sub_mass_cont=0.24159)
S 0066-09-09 19.583h:    0.00000    0.00126          0.00137          0.32947
PISM WARNING:  KSPSolve() reports 'diverged'; reason = -4 = 'DIVERGED_DTOL'
  writing linear system to PETSc binary file SSAFD_kspdivergederror.petsc ...
  re-trying using the Additive Schwarz preconditioner...
PISM WARNING:  KSPSolve() reports 'diverged'; reason = -4 = 'DIVERGED_DTOL'
  writing linear system to PETSc binary file SSAFD_kspdivergederror.petsc ...
PISM ERROR: SSAFD KSP (linear solver) failed: DIVERGED_DTOL
            while updating the stress balance
            while performing a time step. (Note: Model state was saved to 'LH_Spin_10_100_300m_stressbalance_failed.nc'.)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
```

If I remove the SSA from the hybrid stress model it runs to completion, so it is definitely as the error code says an issue with SSA. 

From here I do not know where to start looking to sort out the issue. 

Would you have any suggestions or ideas on how to solve this issue? If you require further information please do not hesitate to ask here and I shall try and provide ASAP.

Ethan

**Comment by eleeice** [comment]
Update:
After installing the newest version of PISM (2.0.4) onto my VM that is clearly not the issue.
I then ran my model on another HPC I have access to, but it has PISM 1.2 installed and it worked on there also. 
(ALL WITH SSA enabled).

Must be an issue with the HPC?

**Comment by ckhroulev** [comment]
Please re-open if this is still relevant and [make sure you provide all the information needed to reproduce your issue](http://www.pism.io/docs/contributing/bug-reporting.html).
