### ISSUE TITLE
Conservative regridding (averaging) for 2D fields

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#515]
For each grid resolution, I am currently creating a separate file from BedMachine by using `gdal`'s averaging method. This results in a large amount of input files, often duplicated across projects.

`gdal`'s averaging method is very fast, and I'm thus wondering if we could implement a similar approach to regrid spatial fields (basically bedrock and ice thickness). 

If memory serves me well, we once had a python script that could do averaging but I cannot find it anymore.

 Ideally, PISM should be able to `bootstrap` from `BedMachine` directly, with some limitations. This would also facilitate cloud computing.

**Comment by ckhroulev** [comment]
I made quite a bit of progress on this. The latest code is in https://github.com/ckhroulev/pism-interpolation.

**Comment by ckhroulev** [comment]
Done in the `dev` branch; see  #546.
