### ISSUE TITLE
Black-hole calving

### ISSUE THREAD

**Issue by crodehacke** [pism/pism#521]
**Description**

If you create a hole in a floating ice shelf, the calving parameterizations may create icebergs that are removed for numerical stability. At the next time step, calving may create further icebergs, which are removed. Ultimately, the ice shelf starts to disintegrate from the interior due to a single hole. Since the mass is subtracted and discarded, it is gone for ever, like mass fallen into a cosmic black hole.

Please see the following sequence of basal melting rates (left colorbar) of floating ice, grounded ice (dark gray), and ice-free ground (light gray). The figure represents the Ross Ice Shelf as part of the Antarctica.

![Bmelt_movie RIS](https://user-images.githubusercontent.com/16653854/235932470-c01d076f-c7d2-4128-8de6-607afdfea125.gif)

**PISM version**

Based on V 1.2

**To Reproduce**

Punch holes in the Ross Ice Shelf and run the code.

**Expected behavior**

In reality, icebergs in such a hole may create a melange that stabilizes the hole. Therefore, I would consider to turn off iceberg calving in an ocean point which is surrounded by ice. I call such an ocean point enclosed ocean point.

**Additional context**

I've coded a fix based on ideas utilized by the `IcebergRemover` and _connected-compentes_ (see https://github.com/ckhroulev/connected-components).

**Comment by crodehacke** [comment]
As mentioned, I have coded a fix. To highlight its performance, I have punched holes in parts of Antarctica. These holes are highlighted as white patches and points in the following figure, which shows only a subset of the entire Antarctica domain for clarity.
![DefinedHoles](https://user-images.githubusercontent.com/16653854/235933385-6caa0261-52a1-4037-b317-2e7958f49745.png)

**Comment by crodehacke** [comment]
Depending if the hole-detection and suppressed calving of enclosed ocean points is active, after several time steps, you could see the different behavior.
![HolesEvolution](https://user-images.githubusercontent.com/16653854/235934227-b6d1b825-17ff-4a1e-beb2-bc62837f1fe6.png)

If the hole detection is active and calving is suppressed of by ice enclosed ocean points, the punched holes do not growth in floating ice. Holes in grounded ice is in generally filled by lateral inflow from surrounding ice (left subfigure).

If the hole detection is deactivate (current PISM standard), iceberg calving starts to increase holes by the growing ocean fraction (dark blue) in ice shelves marked by the light-blue color. The growth of holes is pronounced of one grid box holes in the Ross Ice Shelf, where these holes started to merge and create a C-like structure representing an open ocean. Also, the bigger square hole in the Filchner-Ronne-Ice Shelf expands to the left side.

**Comment by crodehacke** [comment]
As a side-effect of the hole detection and subsequent calving suppression in ice shelf holes, other fringing ice shelves seem to be subject to less calving, as the thickness difference plots highlights, representing the thickness difference at the same time as the former figure (https://github.com/pism/pism/issues/521#issuecomment-1533069520).

![HolesTHKDiff_white](https://user-images.githubusercontent.com/16653854/235937484-be96c58c-7ff9-42f9-b506-55a66167402a.png)

**Comment by crodehacke** [comment]
I want to share the code as an independent branch named `detect_holes`, but I may not have sufficient rights to do so:
```
> git push origin detect_holes
ERROR: Permission to pism/pism.git denied to crodehacke.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```
while
```
> git remote -v | grep origin
origin	git@github.com:pism/pism.git (fetch)
origin	git@github.com:pism/pism.git (push)
```
and successful authentication seems to work
```
> ssh -T git@github.com
Hi crodehacke! You've successfully authenticated, but GitHub does not provide shell access.
```
If deemed helpful, I can integrate these changes into the newest branch once I can create branches and push code to these branches.

**Comment by crodehacke** [comment]
> Christian, you have to push your changes to your personal PISM repo. If your repository is public, everybody can access your changes and you could also create a pull request from there.

Thanks, Sebastian, but how do I create a pull request to an independent repository which has not been forked within github.com? 
Or, more specifically: How do I create a pull request in `pism/pism` fetching from https://github.com/crodehacke/PISMcr/tree/detect_holes?

**Comment by sebhinck** [comment]
Create a fork of the original PISM.
Add that fork as a remote of your "PISMcr" repository and push your branch to your forked repo.

**Comment by crodehacke** [comment]
Thanks for offering help but I do not understand.

> Create a fork of the original PISM. Add that fork as a remote to your "PISMcr" repository and push your branch to your forked repo.

I can easily fork the original pism repro in the web interface, but I have no idea how to add a remote via the web interface to this forked repro; a g*-search has been helpful too.
I know how to add a remote at the terminal, and my local repro knows about the original PISM repro.

### Questions:

1. > Create a fork of the original PISM.  

On the web interface or on the local terminal? In the latter case, it would be called "clone", or?

2. > Add that fork as a remote to your "PISMcr" repository ...

If on the web,  how?
If on the local terminal, what is the difference from just adding the remote original pism to the local repository?

3. > ... push your branch to your forked repo.

Can not tell, because I already fail with the suggestions above.

**Comment by ckhroulev** [comment]
@crodehacke Thanks for reporting this! I really appreciate that you have a fix you can contribute, however PISM already has almost all the necessary code in the PICO sub-shelf melt model.

I can more-or-less copy-and-paste it from there.

Thanks again!

**Comment by crodehacke** [comment]
> Christian: I sent you an invite to collaborate. Accept it and you should be able to push. Andy

It works. Thanks!

**Comment by crodehacke** [comment]
> ... PISM already has almost all the necessary code in the PICO sub-shelf melt model.
> 
> I can more-or-less copy-and-paste it from there.

@ckhroulev: That sounds lovely; just for curiously, a few questions about your ideas.

- Would it work for all calving parameterizations, even if we do not use PICO?
- What is about frontal melting? (in my code I have not turned it off (yet) but it might be a good idea if we could deactivate frontal melting via an external switch too).

Have a lovely day!

**Comment by ckhroulev** [comment]
I meant to say that PICO already has code identifying "ice free ocean" areas that are not connected to the global ocean. 

https://github.com/pism/pism/blob/e55a283827dc1758305ff66f1a1f5f68e14f126e/src/coupler/ocean/PicoGeometry.cc#L494-L523

We can use this to identify ice front locations where calving (and possibly frontal melt) should be inactive.

The definition of "global ocean" used by this implementation is "the largest (by area) contiguous patch of "ice free ocean" cells". We can choose a different definition, if necessary.

> - Would it work for all calving parameterizations, even if we do not use PICO?

Yes. It would require a little bit of work to make sure all implemented parameterizations behave, but this *is* what I have in mind.

> - What is about frontal melting? (in my code I have not turned it off (yet) but it might be a good idea if we could deactivate frontal melting via an external switch too).

We can make this work.

**Comment by crodehacke** [comment]
Just perfect!

**Comment by JohannesFeldmann** [comment]
@crodehacke @ckhroulev Highly appreciated that you brought up this issue and now solve it as I ran into similar problems with some of my simulations!
