### ISSUE TITLE
no difference between ncap scripts in doc/sphinx/manual/practical-usage/conservation

### ISSUE THREAD

**Issue by bueler** [pism/pism#530]
**Description**

In currrent main branch:
```
$ diff ice_mass_accounting_error.txt scalar_accounting_error.txt 
4d3
<    tendency_of_ice_mass_due_to_surface_mass_flux +
5a5
>    tendency_of_ice_mass_due_to_surface_mass_flux +
```
(That is, there is no difference except a new line at end of file or something).

I think the `scalar_accounting_error.txt` should be different, but I am not (yet) clear on what the quantities should be.

**Comment by bueler** [comment]
I think maybe I have misunderstood here.  Maybe the two scripts _should_ be the same.

In that case I think it would be helpful on the page https://www.pism.io/docs/manual/practical-usage/mass-conservation.html to remind the user that variables coming from `-ts_file X -ts_vars ...` may have the same name as those from `-extra_file X -extra_vars ...`, but that the former are already integrated over space?

**Comment by ckhroulev** [comment]
> I think maybe I have misunderstood here.

This is correct.

> I think it would be helpful <...> to remind the user that variables coming from `-ts_file X -ts_vars ...` may have the same name as those from `-extra_file X -extra_vars ...`, but that the former are already integrated over space?

Sure! Please feels free to make the appropriate edits.
