### ISSUE TITLE
Add "tendency_of_ice_mass_due_to_grounding_line_flux"

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#539]
**Is your feature request related to a problem? Please describe.**
No.

**Describe a solution you would like to have**
The spatial field `grounding_line_flux` is reported in `kg m-2 year-1`, which requires ice thickness and grid resolution to approximate mass change in `Gt year-1`.
Computing `tendency_of_ice_mass_due_to_grounding_line_flux` similar to `tendency_of_ice_mass_due_to_discharge` should be straightforward.

**Describe alternatives you've considered**
None.

**Additional context**
This convenience field is needed for comparison with observations.

**Comment by ckhroulev** [comment]
Done in the `dev` branch.
