### ISSUE TITLE
regional *diagnostic* tools as important as modeling tools?

### ISSUE THREAD

**Issue by bueler** [pism/pism#66]
This is a thought, but it may become a task _after_ 0.5.

Feedback wanted.

Rhetorical question: What is the drainage basin mask (DBM) _for_?

Answer currently: DBM = `ftt_mask`, which controls the `-force_to_thk` mechanism.

I am guessing that modelers actually want and expect this answer:  The DBM determines in what region all scalar diagnostics are computed.  E.g. new meaning of `ivol` is "volume of ice inside DBM=1 region, where DBM is in file X.nc".  How hard would it be to mask diagnostics regionally like this?

The `no_model_mask` concept and implementation is fine as far as I can tell.  It contains much of the meaning of regional modeling, namely model isolation.  No change there.

I do not quite understand how important the  `-force_to_thk` mechanism is in practice.  (Trying the `jako/` example without it seems to cause the SSA solver to struggle unreasonably, and I am not sure why; it could be more or less fundamental or technical.)  But even if it is not a critical mechanism, it is a reasonable idea.  I assume we should keep it anyway.

**Comment by ckhroulev** [comment]
I still agree that it is not hard to mask diagnostics, but now (7 years later) I am not convinced that this masking should be done in PISM. (Implementing it in PISM means more code to write, debug, test, and maintain.)

Please re-open this issue if you disagree.

**Comment by bueler** [comment]
Fair enough.  It is hard to know the user's intended mask semantics, yes?

**Comment by ckhroulev** [comment]
> It is hard to know the user's intended mask semantics, yes?

It is, indeed.
