### ISSUE TITLE
Grounding line does not move when becoming boundary...

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#79]
Observation: The grounding line is free to evolve as long as an ice shelf is attached, but when the ice-shelf-front boundary retreats by calving or melting up to the grounding line the flux through the grounded boundary drops immediately (by several orders of magnitude). Ice thickness in the grounded boundary cell increases accordingly such that due to the increasing surface gradient the flux increases slightly, but still much lower than for the case of an attached ice shelf. 

Test: Starting with the linearly sloping MISMIP setup (in steady state) with attached ice shelf we could find out more details about this (numerical) issue when using thickness calving (and hence a retreating front). Since it is flowline (no buttressing) upstream values remain unchanged for a retreating steady ice shelf.

See http://www.pik-potsdam.de/~albrecht/grounding_line_bug/run.sh

The problem occurs in the SSA iterations:
1) In the moment the boundary becomes grounded several iteration loops are needed for convergence
2) In assemble_matrix the basal shear term depends on the constant tauc in the numerator and on the velocity magnitude of the last SSA loop in the denominator: If velocities are small, basal shear is large.
3) This term then enters the matrix in order to find the right velocity components, which balances the product of matrix and velocity vector with the right hand side (rhs), where we have the driving stress and the resultant forcing term of the cfbc.
4) After the first outer loop, calculated velocities have decreased at the boundary, while the viscosity and basal shear term has increased accordingly, which enters again the matrix for the next outer loop.
5) This goes on for each outer SSA iteration within one time step reducing then "abruptly" the flux at the boundary to almost 0 (bounded by a regularization parameter), until reaching convergence

Options:

a) When using the option -cfbc we see for the last grounded cell in flow direction (green) a drastic drop in velocity to almost zero (bounded by regularization), after the last ice shelf cell calves off (black). Also the grounded cells upstream are affected (blue, white and red). Ice flux increases in the following hundred years due to a more than doubling in terminal ice thickness. See also the related outfiles and plots...

See http://www.pik-potsdam.de/~albrecht/grounding_line_bug/cfbc.png

b) A similar but not so extreme drop occurs when not using the calving front boundary condition (-cfbc). Here velocity gradients over the boundary are taken into account (in the SSA matrix) with zero velocity on the ocean. This might be different when using the artificial shelf extension.

See http://www.pik-potsdam.de/~albrecht/grounding_line_bug/no_cfbc.png

c) Also for a pseudo_q=1(according to MISMIP exp 2b) the result does not change qualitatively. We thought that the resultant denominator would equal 1 independent of velocity.

See http://www.pik-potsdam.de/~albrecht/grounding_line_bug/cfbc_q1.png

d) We also tried different combinations of ksp_type (cg, bicg, gmres, bcgs, cgs, tfqmr, tcqmr, and cr) and pc_type bjacobi/asm -sub_pc_type ilu/lu, which did not improve the result for the last grounded grid cell.

e) Putting the basal drag term to the rhs dependent on the (old) velocities of the previous time step unfortunatetly only delayed the drop over several time steps (instead of iterations).

Workaround: In the commit commit 97086240060162d44c775e4aedb57de471642188 in the pik_fracdens branch we implemented an option, which leaves a band of an ice shelf of two cells width when a retreat due to calving occurs. This is quite unphysical but helps to avoid the grounding line bug, at least partly. But this is definitely not a proper fix.

We want to point out that we really need a solution for this bug, especially for the urgent simulations of the Antarctic ice sheet. It seems to be of numerical kind within the framework of the SSA stress balance relaxation. It is most pronounced when using the CFBC at grounded margins and may occur for different reasons in a less extreme way when not using the CFBC. Our skills are limited in this issue so that we seek for help in this issue.

**Comment by ckhroulev** [comment]
Deleted the `dev_glbug_solved` branch (was d506204683b0864e88b53b9d1d1ee8e2b9321415).

**Comment by bueler** [comment]
Since you are so good at lopping-off branches:  http://www.davey.com/job-opportunities/  :smile:

**Comment by ckhroulev** [comment]
Nothing in Alaska. Dang!
